<?php
/**
 * Created by PhpStorm.
 * User: 400005
 * Date: 11/03/2019
 * Time: 12:02
 */ ?>
<ons-row id="prof_found">
    <ons-col style="padding: 0 10px">
        <ons-card modifier="material">
            <div class="title">
                <h2 class="card__title" style="text-align: center;">Profissionais encontrados</h2>
            </div>
            <div class="content">
                <ons-row>
                    <ons-list style="width: 100%" modifier="inset">
                        <ons-lazy-repeat>
                            <?php foreach ($this->profissionais as $p): ?>
                                <ons-list-item expandable modifier="longdivider">
                                    <?= $p['user_information']['user_name'] ?>
                                    <div class="expandable-content">
                                        <ons-row>
                                            <ons-col width="100%">
                                                <p></p>
                                                <p>Endereço: <?= $p['user_information']['user_addr'] ?></p>
                                                <ons-row>
                                                    <ons-col width="35%"></ons-col>
                                                    <ons-col width="65%" style="text-align: right">
                                                        <ons-button onclick="fn.viewDetails()" ripple modifier="material" class="right-align">
                                                            Mais informações
                                                        </ons-button>
                                                    </ons-col>
                                                </ons-row>
                                            </ons-col>
                                        </ons-row>
                                    </div>
                                </ons-list-item>
                            <?php endforeach; ?>
                        </ons-lazy-repeat>
                    </ons-list>
                </ons-row>
            </div>
        </ons-card>
    </ons-col>
</ons-row>
