<ons-navigator swipeable id="mainNavigator" page="mainPage.html"></ons-navigator>

<template id="mainPage.html">
    <ons-page id="mainPage">
        <ons-toolbar>
            <div class="center">SIGAS</div>
        </ons-toolbar>
        <ons-tabbar swipeable position="bottom">
            <ons-tab page="tab1.html" label="Inicio" icon="fa-medkit" active>
            </ons-tab>
            <ons-tab page="tab2.html" label="Histórico" icon="fa-history">
            </ons-tab>
            <ons-tab page="tab3.html" label="Perfil" icon="fa-user-circle">
            </ons-tab>
        </ons-tabbar>
    </ons-page>
</template>

<template id="professionalsPage.html">
    <ons-page id="professionalsPage">
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Busca</ons-back-button>
            </div>
            <div class="center"></div>
        </ons-toolbar>
        <ons-row id="fResultados">

        </ons-row>
    </ons-page>
</template>

<template id="detailsPage.html">
    <ons-page id="detailsPage">
        <ons-toolbar modifier="noshadow" style="background-color: aliceblue !important;">
            <div class="left">
                <ons-back-button>Busca</ons-back-button>
            </div>
            <div class="center"></div>
        </ons-toolbar>
        <ons-row id="fInformacoes">

        </ons-row>
        <ons-bottom-toolbar onclick="fn.checkDates(0)">
            <ons-row>
                <ons class="col"></ons>
                <ons class="col" style="padding-top: 10px">SOLICITAR CONSULTA</ons>
                <ons class="col"></ons>

            </ons-row>
        </ons-bottom-toolbar>
    </ons-page>
</template>

<template id="checkDatePage.html">
    <ons-page id="checkDate">
        <ons-toolbar modifier="noshadow" style="background-color: aliceblue !important;">
            <div class="left">
                <ons-back-button>Informações</ons-back-button>
            </div>
            <div class="center"></div>
        </ons-toolbar>
    </ons-page>
</template>

<template id="tab1.html">
    <ons-page id="Tab1">
        <ons-row>
            <ons-col style="padding: 0 10px">
                <ons-card modifier="material">
                    <div class="title">
                        <h2 class="card__title" style="text-align: center;">Qual especialidade você procura?</h2>
                    </div>
                    <div class="content">
                        <ons-row>
                            <ons-col width="100%">
                                <ons-list style="width: 100%; margin: 0" modifier="inset material" id="fSelectEsp">
                                    <ons-lazy-repeat>
                                    </ons-lazy-repeat>
                                </ons-list>
                            </ons-col>
                        </ons-row>
                    </div>
                </ons-card>
            </ons-col>
        </ons-row>
    </ons-page>
</template>

<template id="tab2.html">
    <ons-page id="Tab2">
        <p style="text-align: center;">
            This is the second page.
        </p>
    </ons-page>
</template>
<template id="tab3.html">
    <ons-page id="Tab3">
        <p style="text-align: center;">
            This is the third page.
        </p>
    </ons-page>
</template>


<script>
    $(function () {
        // $(document)[0].addEventListener('prechange', function(event) {
        //     $('ons-toolbar .center')
        //         .innerHTML = event.tabItem.getAttribute('label');
        // });
        if (ons.isReady()) {
            $.get("/mobile/get-especialidades", {}, function (data) {
                $.each(data[0], function (key, value) {
                    $("#fSelectEsp ons-lazy-repeat").append('<ons-list-item modifier="chevron longdivider" onclick="fn.selectP('+value.id+')" tappable>' + value.desc_especialidade + '</ons-list-item>');
                });
            });
            // $("#fSelectEsp").change(function () {
            //     console.log("Called")
            //     console.log($("#Tab1 .page__content"))
            //     $.get("/mobile/get-profissionais", {esp: $(this).val()}, function (data) {
            //         if ($("#Tab1 .page__content #prof_found").length)
            //             $("#Tab1 .page__content #prof_found").remove();
            //         $("#Tab1 .page__content").append(data);
            //     })
            // });
        }


        fn = {};

        fn.alert = function(){
            console.log("Called", $("#alert"));
            let dialog = $('#alert');

            if (dialog) {
                dialog.show();
            } else {
                ons.createElement('dialog.html', { append: true })
                    .then(function(dialog) {
                        dialog.show();
                    });
            }
        };

        fn.hideDialog = function(id) {
            document
                .getElementById(id)
                .hide();
        };

        fn.viewDetails = function (id) {
            let html;
            $.get('/mobile/get-profissional-info', {id_user: id}, function (data) {
                html = data;
            }).then(function () {
                $('#mainNavigator')[0].pushPage('detailsPage.html', {data: {id: "A"}}).then(function () {
                    $('#fInformacoes').empty();
                    $('#fInformacoes').append(html);
                });
            });
        };

        fn.checkDates = function(id){
          $("#mainNavigator")[0].pushPage('checkDatePage.html');
        };

        fn.selectP = function (id) {
            let html;
            $.get("/mobile/get-profissionais", {esp: id}, function (data) {
                html = data;
                // if ($("#Tab1 .page__content #prof_found").length)
                //     $("#Tab1 .page__content #prof_found").remove();
                // $("#Tab1 .page__content").append(data);
            }).then(function () {
                $('#mainNavigator')[0].pushPage('professionalsPage.html').then(function () {
                    $('#fResultados').empty();
                    $('#fResultados').append(html);
                })
            });
        };

        fn.open = function () {
            $("#menu")[0].open();
        };

        fn.load = function (page) {
            let content = $('#content')[0],
                menu = $('#menu')[0];
            content.load(page).then(menu.close.bind(menu));
        };
    });

</script>