<ons-navigator swipeable id="mainNavigator" page="mainPage.html"></ons-navigator>

<template id="mainPage.html">
    <ons-page id="mainPage">
        <ons-toolbar>
            <div class="center">SIGAS</div>
        </ons-toolbar>
        <ons-tabbar swipeable position="bottom" id="mainTabbar">
            <?php if ($this->userstate): ?>
                <ons-tab page="tab1.html" label="Inicio" icon="fa-medkit" active>
                </ons-tab>
                <ons-tab page="tab2.html" label="Histórico" icon="fa-history">
                </ons-tab>
                <ons-tab page="tab3.html" label="Perfil" icon="fa-user-circle">
                </ons-tab>
            <?php else: ?>
                <ons-tab page="tab1.html" label="Inicio" icon="fa-medkit" active>
                </ons-tab>
                <ons-tab page="tab3.html" label="Login" icon="fa-user-circle">
                </ons-tab>
            <?php endif; ?>
        </ons-tabbar>
    </ons-page>
</template>

<template id="professionalsPage.html">
    <ons-page id="professionalsPage">
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Busca</ons-back-button>
            </div>
            <div class="center">Resultados</div>
        </ons-toolbar>
        <ons-row id="fResultados">
        </ons-row>
    </ons-page>
</template>

<template id="detailsPage.html">
    <ons-page id="detailsPage">
        <ons-toolbar modifier="noshadow" style="background-color: aliceblue !important;">
            <div class="left">
                <ons-back-button>Busca</ons-back-button>
            </div>
            <div class="center"></div>
        </ons-toolbar>
        <ons-row id="fInformacoes">
        </ons-row>
        <ons-bottom-toolbar onclick="fn.checkDates($('#profid').val())">
            <ons-row>
                <ons class="col"></ons>
                <ons class="col" style="padding-top: 10px">SOLICITAR PROCEDIMENTO</ons>
                <ons class="col"></ons>

            </ons-row>
        </ons-bottom-toolbar>
    </ons-page>
</template>

<template id="checkDatePage.html">
    <ons-page id="checkDate">
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Informações</ons-back-button>
            </div>
            <div class="center"></div>
        </ons-toolbar>
        <ons-row>
            <ons-col>
                <ons-card>
                    <div class="title">Selecione uma data abaixo:</div>
                    <div id="callendarArea" style="margin: 10px 0"></div>
                </ons-card>
            </ons-col>
        </ons-row>
    </ons-page>
</template>

<template id="finishAppoint.html">
    <ons-page id="finishAppoint">
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Data</ons-back-button>
            </div>
            <div class="center"></div>
        </ons-toolbar>
        <ons-row>
            <ons-col>
                <ons-card>
                    <div class="title">Preencha as informações para agendamento:</div>
                    <ons-list>
                        <form action="<?= $this->url('application_mobile', ["action" => "save-appoint"]) ?>"
                              method="post" enctype="multipart/form-data" id="form-appoint">
                            <ons-list-header>Data desejada:</ons-list-header>
                            <ons-list-item class="input-items">
                                <div>
                                    <input type="text" class="text-input" name="fDataReq" id="req-date" readonly>
                                </div>
                            </ons-list-item>
                            <ons-list-header>Procedimento desejado:</ons-list-header>
                            <ons-list-item class="input-items">
                                <div>
                                    <select class="select-input select-input--material" name="fProcdReq" id="req-procd">
                                        <option value="1">Option 1</option>
                                        <option value="2">Option 2</option>
                                        <option value="3">Option 3</option>
                                    </select>
                                </div>
                            </ons-list-item>
                            <ons-list-header>Horário desejado:</ons-list-header>
                            <ons-list-item class="input-items">
                                <div>
                                    <input type="time" class="text-input text-input--material" name="fHoraReq"
                                           id="req-date">
                                </div>
                            </ons-list-item>
                            <div class="form-params" style="display: none">
                                <input type="text" id="idProf" name="fIdProf">
                            </div>
                        </form>
                    </ons-list>
                </ons-card>
            </ons-col>
        </ons-row>
        <ons-bottom-toolbar onclick="fn.sendAppointment()">
            <ons-row>
                <ons class="col"></ons>
                <ons class="col" style="padding-top: 10px">FINALIZAR SOLICITAÇÃO</ons>
                <ons class="col"></ons>
            </ons-row>
        </ons-bottom-toolbar>
    </ons-page>
</template>

<template id="tab1.html">
    <ons-page id="Tab1">
        <ons-row>
            <ons-col style="padding: 0 10px">
                <ons-card modifier="material">
                    <div class="title">
                        <h2 class="card__title" style="text-align: center;">Qual especialidade você procura?</h2>
                    </div>
                    <div class="content">
                        <ons-row>
                            <ons-col width="100%">
                                <ons-list style="width: 100%; margin: 0" modifier="inset material" id="fSelectEsp">
                                    <ons-lazy-repeat>
                                    </ons-lazy-repeat>
                                </ons-list>
                            </ons-col>
                        </ons-row>
                    </div>
                </ons-card>
            </ons-col>
        </ons-row>
        <script>
            ons.getScriptPage().onInit = function () {
                fn.especialidadeList();
            }
        </script>
    </ons-page>
</template>

<template id="tab2.html">
    <ons-page id="Tab2">
        <ons-row>
            <ons-col style="padding: 0 10px">
                <ons-card modifier="material">
                    <div class="title">
                        <h2 class="card__title" style="text-align: center;"></h2>
                    </div>
                    <div class="content">
                        <ons-row>
                            <ons-col width="100%">
                                <ons-list style="width: 100%; margin: 0" modifier="inset material" id="fHist">
                                    <ons-lazy-repeat>
                                        <ons-list-item modifier="chevron longdivider"
                                                       onclick="fn.viewHistory()" tappable>
                                            Consulta
                                        </ons-list-item>
                                        <ons-list-item modifier="chevron longdivider"
                                                       onclick="fn.viewHistory()" tappable>
                                            Exame
                                        </ons-list-item>
                                    </ons-lazy-repeat>
                                </ons-list>
                            </ons-col>
                        </ons-row>
                    </div>
                </ons-card>
            </ons-col>
        </ons-row>
        <script>
            ons.getScriptPage().onInit = function () {
                //$.get('')
            }
        </script>
    </ons-page>
</template>

<template id="tab3.html">
    <ons-page id="Tab3">
        <div id="form-area">
        </div>
        <script>
            ons.getScriptPage().onInit = function () {
                fn.profileHandler($(this));
            }
        </script>
    </ons-page>
</template>

<template id="singupForm.html">
    <ons-page id="singup">
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Login</ons-back-button>
            </div>
            <div class="center">
                Cadastro
            </div>
        </ons-toolbar>
        <ons-card>
            <form action="<?= $this->url('singup') ?>" method="post" enctype="multipart/form-data">
                <ons-row>
                    <ons-col width="100%">
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="md-email" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 80%" modifier="material" id="username" name="fEmail"
                                       placeholder="Email" type="email"
                                       float required validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-key" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 80%" id="password" modifier="material" name="fPass" type="password"
                                       placeholder="Senha" float required validate></ons-input>
                        </ons-list-item>
                        <ons-list-item>
                            <div class="right right-label">
                                <button type="submit" class="button">Cadastrar</button>
                            </div>
                        </ons-list-item>
                    </ons-col>
                </ons-row>
            </form>
        </ons-card>
        <style>
            .list-item__center, .list-item__right {
                background-image: none;
            }
        </style>
    </ons-page>
</template>

<template id="editInfoForm.html">
    <ons-page id="editInfoForm">
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Perfil</ons-back-button>
            </div>
            <div class="center">
                Editar informações
            </div>
        </ons-toolbar>

        <ons-card>
            <form action="<?= $this->url('application_mobile', ["action" => "user-profile"]) ?>" method="post"
                  enctype="multipart/form-data">
                <ons-row>
                    <ons-col width="100%">
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-user" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" modifier="material" id="info_user_name" name="fName"
                                       placeholder="Nome completo" type="text"
                                       float required validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-address-card" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" id="info_user_cpf" modifier="material" name="fCpf"
                                       type="text"
                                       placeholder="CPF" float validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="" class="list-item__icon icon-spacer"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" id="info_user_rg" modifier="material"
                                       name="fRg"
                                       type="text"
                                       placeholder="RG" float validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-plus-square" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-select style="width: 100%" id="info_user_healthcare" modifier="material" name="fPlano"
                                        class="select"
                                        float>
                                <select class="select-input">
                                    <option value="">Selecione seu plano de saúde</option>
                                    <option value="1">Unimed</option>
                                    <option value="2">Hapvida</option>
                                </select>
                            </ons-select>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-map-marker-alt" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" id="info_user_addr" modifier="material" name="fEnd"
                                       type="text"
                                       placeholder="Endereço Residencial" float validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-mobile-alt" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" id="info_user_ctt_phone" modifier="material" name="fTelCel"
                                       type="text"
                                       placeholder="Telefone Celular" float validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-phone" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" id="info_user_ctt_res" modifier="material"
                                       name="fTelRes" type="text"
                                       placeholder="Telefone Residencial" float validate></ons-input>
                        </ons-list-item>
                        <ons-list-item>
                            <div class="right right-label">
                                <button type="submit" class="button">Salvar</button>
                            </div>
                        </ons-list-item>
                    </ons-col>
                </ons-row>
            </form>
        </ons-card>
        <style>
            .list-item__center, .list-item__right {
                background-image: none;
            }

            .icon-spacer::before,
            .icon-blank::before {
                width: 1em;
                content: ' ';
            }
        </style>
        <script>
            ons.getScriptPage().onInit = function () {
                $.get('/mobile/user-profile', {json: true}, function (response) {
                    $.each(response, function (key, value) {
                        if (value !== " " || value !== "" || value !== null) {
                            $("#" + key).val(value);
                        }
                    })
                })
            }
        </script>
    </ons-page>
</template>


<script>
    $(function () {
        if (ons.isReady()) {
            $.get('/mobile/get-log-messages', {}, function (response) {
                if (response.error) {
                    let titleT = "", icontype = "";
                    switch (response.error.code) {
                        case 0:
                            titleT = "Erro";
                            icontype = "error";
                            break;
                        case 1:
                            titleT = "Sucesso";
                            icontype = "success";
                            break;
                        default:
                            titleT = "Erro";
                            icontype = "error";
                            break;
                    }
                    swal({
                        title: titleT,
                        text: response.error.message,
                        timer: 3000,
                        icon: icontype,
                        buttons: false
                    });
                }
            })
        }

        fn = {};

        fn.especialidadeList = function () {
            $.get("/mobile/get-especialidades", {}, function (data) {
                $.each(data[0], function (key, value) {
                    $("#fSelectEsp ons-lazy-repeat").append('<ons-list-item modifier="chevron longdivider" onclick="fn.selectP(' + value.id + ')" tappable>' + value.desc_especialidade + '</ons-list-item>');
                });
            });
        };

        fn.alert = function () {
            console.log("Called", $("#alert"));
            let dialog = $('#alert');

            if (dialog) {
                dialog.show();
            } else {
                ons.createElement('dialog.html', {append: true})
                    .then(function (dialog) {
                        dialog.show();
                    });
            }
        };

        fn.hideDialog = function (id) {
            document
                .getElementById(id)
                .hide();
        };

        fn.viewDetails = function (id) {
            let html;
            $.get('/mobile/get-profissional-info', {id_user: id}, function (data) {
                html = data;
            }).then(function () {
                $('#mainNavigator')[0].pushPage('detailsPage.html').then(function () {
                    $('#fInformacoes').empty();
                    $('#fInformacoes').append(html);
                });
            });
        };

        fn.checkDates = function (id) {
            let state;
            $.get('/user-state', {}, function (response) {
                state = response.state;
            }).then(function () {
                if (state) {
                    $("#mainNavigator")[0].pushPage('checkDatePage.html').then(function () {
                        // $("#calendarArea").fullCalendar({
                        //     monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
                        // });
                        let formatter = new Intl.DateTimeFormat('pt-BR');
                        try {
                            let calendar = new FullCalendar.Calendar($("#callendarArea")[0], {
                                plugins: ['dayGrid', 'timeGrid', 'bootstrap', 'interaction', 'moment', 'momentTimezone'],
                                locale: 'pt-BR',
                                themeSystem: "bootstrap",
                                header: {
                                    left: 'prev,next',
                                    center: 'title',
                                    right: 'dayGridMonth',
                                },
                                buttonText: {
                                    month: 'mês'
                                },
                                fullday: false,
                                height: 600,
                                dateClick: function (info) {
                                    if (info.view.type === 'dayGridMonth') {
                                        calendar.changeView('timeGridDay');
                                        calendar.gotoDate(info.date);
                                    } else if (info.view.type === 'timeGridDay') {
                                        swal({
                                            title: "Confirmação",
                                            text: 'Continuar escolha para data ' + fn.formattDate(info.date) + '?',
                                            buttons: {
                                                no: {
                                                    text: "Não",
                                                    value: false
                                                },
                                                yes: {
                                                    text: "Sim",
                                                    value: true,
                                                    className: 'btn-success'
                                                }
                                            }
                                        }).then(r => {
                                            if (r) {
                                                fn.finishAppointment(info);
                                            }
                                        })
                                    }
                                },
                                views: {
                                    timeGridDay: {
                                        type: 'dayGrid',
                                        duration: {days: 1},
                                        buttonText: 'Day',
                                    }
                                },
                                timeZone: "UTC",
                                eventSources: [
                                    {
                                        url: '/mobile/get-schedule',
                                        method: 'GET',
                                        extraParams: {
                                            id_professional: id
                                        },
                                        failure: function (e) {
                                            console.log("erro" + e.toString());
                                        }
                                    }
                                ]
                            });
                            calendar.render();
                        } catch (e) {
                            console.log(e.message);
                            console.log(e.stack)
                        }
                    });
                } else {
                    swal({
                        title: "Atenção",
                        text: "Você deve estar logado para solicitar um procedimento.",
                        icon: "warning",
                        buttons: false,
                        timer: 4000
                    }).then(() => {
                        $('#mainNavigator')[0].resetToPage('mainPage.html')
                    })
                }
            })

        };

        fn.selectP = function (id) {
            let html;
            $.get("/mobile/get-profissionais", {esp: id}, function (data) {
                html = data;
                // if ($("#Tab1 .page__content #prof_found").length)
                //     $("#Tab1 .page__content #prof_found").remove();
                // $("#Tab1 .page__content").append(data);
            }).then(function () {
                $('#mainNavigator')[0].pushPage('professionalsPage.html').then(function () {
                    $('#fResultados').empty();
                    $('#fResultados').append(html);
                })
            });
        };

        fn.open = function () {
            $("#menu")[0].open();
        };

        fn.load = function (page) {
            let content = $('#content')[0],
                menu = $('#menu')[0];
            content.load(page).then(menu.close.bind(menu));
        };

        fn.singupForm = function () {
            $('#mainNavigator')[0].pushPage('singupForm.html');
        };

        fn.profileHandler = function (page) {
            let html;
            $.get('/user-state', {}, function (data) {
                if (data.state) {
                    $.get('/mobile/user-profile', {}, function (response) {
                        html = response;
                    }).then(function () {
                        page.find('#form-area').empty().append(html);
                    })
                } else {
                    $.get('/mobile/login-form', {}, function (response) {
                        html = response;
                    }).then(function () {
                        page.find('#form-area').empty().append(html);
                    })
                }
            })
        };

        fn.editInfo = function () {
            $('#mainNavigator')[0].pushPage('editInfoForm.html');
        };

        fn.finishAppointment = function (info) {
            $("#mainNavigator")[0].pushPage('finishAppoint.html').then(() => {
                $("#req-date").val(fn.formattDate(info.date));
                $("#idProf").val($("#profid").val());
            });
        };

        fn.sendAppointment = function (data) {
            $("#form-appoint").submit();
        };

        fn.formattDate = function (date) {
            return [(date.getDate() + 1) + '/' + (date.getMonth() + 1) + '/' + date.getFullYear()].join('');
        }
    });

</script>