<?php
/**
 * Created by PhpStorm.
 * User: 400005
 * Date: 18/03/2019
 * Time: 09:22
 */
$infos = $this->prof[0];
//\Application\Debug\UtilsFile::printvar($infos);
?>
<div class="content" style="width: 100%">
    <div class="profile_upper">
        <div class="profile_wrapper">
            <div class="profile_image_wrapper">
                <img src="http://placekitten.com/g/40/40">
            </div>
            <div class="profile_info_wrapper">
                <div class="profile_info_numbers">
                    <div>
                        <div><?= $infos['info_user_name'] ?></div>
                    </div>
                    <div>
                        <div><?= $infos['esp_desc_especialidade'] ?></div>
                    </div>
                    <div>
                        <div id="addr_text"><?= $infos['pi_prof_addresses'][0] ?></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <ons-row class="profile_button_bar_profprofile">
        <ons-col>
            <ons-button id="dadpesp" class="custom-button active" onclick="display('dadpesp', 'profprofile', 0)">
                Informações
            </ons-button>
        </ons-col>
        <ons-col>
            <ons-button id="dadprofp" class="custom-button" icon="fa-checkbox"
                        onclick="display('dadprofp', 'profprofile', 1)">Endereço
            </ons-button>
        </ons-col>
        <ons-col>
            <ons-button id="comentprofp" class="custom-button" icon="fa-checkbox"
                        onclick="display('comentprofp', 'profprofile', 2)">Avaliações
            </ons-button>
        </ons-col>
    </ons-row>
    <ons-row>
        <ons-carousel id="carousel-profprofile">
            <ons-carousel-item>
                <ons-card>
                    <div class="title">Sobre</div>
                    <div class="content">
                        <?= $infos['pi_professional_about'] ?>
                    </div>
                </ons-card>
                <ons-card>
                    <div class="title">Planos de Saúde aceitos</div>
                    <div class="content">
                        <ons-list modifier="nodivider">
                            <?php foreach ($infos['healthcare'] as $hc): ?>
                                <ons-list-item><?= $hc['desc_healthcare'] ?></ons-list-item>
                            <?php endforeach; ?>
                        </ons-list>
                    </div>
                </ons-card>
                <ons-card>
                    <div class="title">Procedimentos disponíveis</div>
                    <div class="content">
                        <ons-list modifier="nodivider">
                            <?php foreach ($infos['procedures'] as $procedure): ?>
                                <ons-list-item><?= $procedure['procedure_description'] ?></ons-list-item>
                            <?php endforeach; ?>
                        </ons-list>
                    </div>
                </ons-card>
            </ons-carousel-item>
            <ons-carousel-item>
                <ons-card>
                    <div class="title">Localização</div>

                    <?php foreach ($infos['pi_prof_addresses'] as $add): ?>
                        <div>
                            <?= $add ?>
                        </div>
                    <?php endforeach; ?>
                    <div class="content">
                        <div id="mapid" style="height: 200px"></div>
                        <a href="#" id="geolink" target="_blank" class="button button--large--quiet">Abrir no Google
                            Maps</a>
                    </div>
                </ons-card>
            </ons-carousel-item>
            <ons-carousel-item>
                <ons-list>
                    <?php if (count($infos['ratings']) === 0): ?>
                        <ons-list-item class="item-custom" modifier="longdivider">
                            <div class="center">
                                <div class="tweet-header">
                                    <span class="list-item__title">Este profissional ainda não foi avaliado</span>
                                    <span class="list-item__subtitle"></span>
                                    </ons-button>
                                </div>
                                <span class="list-item__content" style="font-style: italic"></span>
                                <ons-row class="option-buttons">
                                    <ons-col>
                                    </ons-col>
                                    <ons-col>
                                    </ons-col>
                                    <ons-col>
                                    </ons-col>
                                    <ons-col>
                                    </ons-col>
                                </ons-row>
                            </div>
                        </ons-list-item>
                    <?php endif; ?>
                    <?php foreach ($infos['ratings'] as $rating): ?>
                        <ons-list-item class="item-custom" modifier="longdivider">
                            <div class="left">
                                <img class="list-item__thumbnail" src="http://placekitten.com/g/40/40">
                            </div>
                            <div class="center">
                                <div class="tweet-header">
                                    <span class="list-item__title"><b><?= $rating['user_name'] ?></b></span>
                                    <span class="list-item__subtitle"></span>
                                    </ons-button>
                                </div>
                                <span class="list-item__content"
                                      style="font-style: italic">"<?= $rating['pr_rating_comment'] ?>"</span>
                                <ons-row class="option-buttons">
                                    <ons-col>
                                    </ons-col>
                                    <ons-col>
                                    </ons-col>
                                    <ons-col>
                                    </ons-col>
                                    <ons-col>
                                        <ons-button modifier="quiet">
                                            <span class="reaction-no"><?= $rating['pr_rating_stars'] ?></span>
                                            <ons-icon icon="fa-star"></ons-icon>
                                        </ons-button>
                                    </ons-col>
                                </ons-row>
                            </div>
                        </ons-list-item>
                    <?php endforeach; ?>
                </ons-list>

            </ons-carousel-item>
        </ons-carousel>
    </ons-row>
</div>
<input type="text" readonly id="profid" value="<?= $infos['u_id'] ?>" hidden>
