<ons-navigator swipeable id="mainNavigator" page="mainPage.html"></ons-navigator>

<template id="mainPage.html">
    <ons-page id="mainPage">
        <ons-toolbar>
            <div class="center">SIGAS</div>
        </ons-toolbar>
        <ons-tabbar swipeable position="bottom" id="mainTabbar">
            <ons-tab page="tab1.html" label="Inicio" icon="fa-medkit" active>
            </ons-tab>
            <ons-tab page="tab2.html" label="Histórico" icon="fa-history">
            </ons-tab>
            <ons-tab page="tab3.html" label="Perfil" icon="fa-user-circle">
            </ons-tab>
        </ons-tabbar>
    </ons-page>
</template>

<template id="tab1.html">
    <ons-page id="Tab1">
        <ons-list class="header-custom" style="background-color: #fafafa">
            <ons-list-item class="input-items">
                <ons-search-input id="search-input" maxlength="20" placeholder="Buscar profissional por nome"
                                  style="width: 80%;margin-right: 20px"></ons-search-input>
                <button class="button button--light" id="search-button">
                    <ons-icon icon="fa-search"></ons-icon>
                </button>
                <ons-select id="select-input" style="width: 20%; margin-left: 10px; display: none">
                    <option value="name">
                        Nome
                    </option>
                    <option value="React">
                        Especialidade
                    </option>
                    <option value="Angular">
                        Endereço
                    </option>
                </ons-select>
            </ons-list-item>
        </ons-list>
        <ons-row>
            <ons-col style="padding: 0">
                <ons-list id="list-profs">
                    <ons-lazy-repeat>
                        <ons-progress-circular indeterminate></ons-progress-circular>
                    </ons-lazy-repeat>
                </ons-list>
            </ons-col>
        </ons-row>
        <script>
            ons.getScriptPage().onInit = function () {
                profissionaisList();
                $("#search-input").focusout(function () {
                    profissionaisList($(this).val())
                }).keypress(function (event) {
                    let keycode = (event.keyCode ? event.keyCode : event.which);
                    if (keycode === '13') {
                        profissionaisList($(this).val())
                    }
                });
                $("#search-button").click(function () {
                    profissionaisList($("#search-input").val())
                })
            }
        </script>
    </ons-page>
</template>

<template id="tab2.html">
    <ons-page id="Tab2">
        <ons-row class="profile_button_bar_historic">
            <ons-col>
                <ons-button id="proc" class="custom-button active" onclick="display('proc', 'historic', 0)">
                    Procedimentos
                </ons-button>
            </ons-col>
            <ons-col>
                <ons-button id="presc" class="custom-button"
                            onclick="display('presc', 'historic', 1)">Prescrições
                </ons-button>
            </ons-col>
        </ons-row>
        <ons-row>
            <ons-carousel fullscreen id="carousel-historic" style="width: 100%">
                <ons-carousel-item>
                    <ons-list class="header-custom">
                        <ons-list-item class="input-items">
                            <div style="width: 60%">Filtrar resultados:</div>
                            <ons-select id="history-filter" onchange="viewHistory()"
                                        style="width: 30%; margin-left: 10px" readonly>
                                <option value="1" selected>
                                    Consulta
                                </option>
                                <!--                                <option value="2">-->
                                <!--                                    Exame-->
                                <!--                                </option>-->
                            </ons-select>
                        </ons-list-item>
                    </ons-list>
                    <ons-row>
                        <ons-col width="100%">
                            <ons-list style="width: 100%; margin: 0" modifier="inset material" id="historyList">
                                <ons-lazy-repeat>

                                </ons-lazy-repeat>
                            </ons-list>
                        </ons-col>
                    </ons-row>
                </ons-carousel-item>
                <ons-carousel-item>
                    <ons-row>
                        <ons-col style="padding: 0">
                            <ons-list id="list-presc">
                                <ons-lazy-repeat>
                                    <ons-progress-circular indeterminate></ons-progress-circular>
                                </ons-lazy-repeat>
                            </ons-list>
                        </ons-col>
                    </ons-row>
                </ons-carousel-item>
            </ons-carousel>
        </ons-row>
        <script>
            ons.getScriptPage().onInit = function () {
                viewHistory();
                loadPrescription();
            }
        </script>
    </ons-page>
</template>

<template id="tab3.html">
    <ons-page id="Tab3">
        <div id="form-area">
            <div class="content" style="width: 100%">
                <div class="profile_upper" style="padding: 14px 6px 14px 16px;">
                    <div class="profile_wrapper">
                        <div class="profile_image_wrapper">
                            <img src="assets/img/profile-image-08.png">
                        </div>
                        <div class="profile_info_wrapper">
                            <div class="profile_info_numbers">
                                <div>
                                    <div><?= $this->user['info_user_name'] === null ?
                                            "Não informado" :
                                            $this->user['info_user_name'] ?></div>
                                </div>
                            </div>
                        </div>
                        <div class="profile_info_wrapper">
                            <div class="logoff">
                                <a href="<?= $this->url('logout') ?>">
                                    <ons-toolbar-button style="float: right; ">
                                        <ons-icon icon="ion-log-out"></ons-icon>
                                    </ons-toolbar-button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <ons-row class="profile_button_bar_profile" hidden>
                    <ons-col>
                        <ons-button id="dadpes" class="custom-button active" onclick="display('dadpes', 'profile', 0)">
                            Pessoal
                        </ons-button>
                    </ons-col>
                    <ons-col>
                        <ons-button id="dadprof" class="custom-button" icon="fa-checkbox"
                                    onclick="display('dadprof', 'profile', 1)">Profissional
                        </ons-button>
                    </ons-col>
                </ons-row>
                <ons-carousel id="carousel-profile">
                    <ons-carousel-item>
                        <ons-card>
                            <div class="title">Dados Pessoais
                                <ons-toolbar-button style="float: right; padding: 0" onclick="editInfo()">
                                    <ons-icon icon="ion-edit"></ons-icon>
                                </ons-toolbar-button>
                            </div>

                            <div class="content">
                                <div class="profile_wrapper">
                                    <div class="profile_info_wrapper">
                                        <div class="profile_info_numbers">
                                            <div>
                                                <div class="profile_info_text">Nome</div>
                                                <div><?= $this->user['info_user_name'] === null ?
                                                        "Não informado" :
                                                        $this->user['info_user_name'] ?></div>
                                            </div>
                                            <div>
                                                <div class="profile_info_text">CPF</div>
                                                <div><?= $this->user['info_user_cpf'] ?></div>
                                            </div>
                                            <div>
                                                <div class="profile_info_text">Endereço</div>
                                                <div><?= $this->user['info_user_addr'] ?></div>
                                            </div>
                                            <div>
                                                <div class="profile_info_text">Plano de Saúde</div>
                                                <div><?= $this->user['desc_healthcare'] ?></div>
                                            </div>
                                            <div>
                                                <div class="profile_info_text">Números de contato</div>
                                                <div>Telefone
                                                    Celular:<?= $this->user['info_user_ctt_phone'] ?></div>
                                                <div>Telefone
                                                    Residencial:<?= $this->user['info_user_ctt_res'] ?></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </ons-card>
                    </ons-carousel-item>
                    <ons-carousel-item>
                        <ons-card>
                            <div class="title">Prescrições disponíveis</div>
                        </ons-card>
                    </ons-carousel-item>
                </ons-carousel>
            </div>
        </div>
    </ons-page>
</template>

<template id="editInfoForm.html">
    <ons-page id="editInfoForm">
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Perfil</ons-back-button>
            </div>
            <div class="center">
                Editar informações
            </div>
        </ons-toolbar>

        <ons-card>
            <form action="<?= $this->url('application_mobile_user', ["action" => "profile"]) ?>" method="post"
                  enctype="multipart/form-data">
                <ons-row>
                    <ons-col width="100%">
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-user" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" modifier="material" id="info_user_name" name="fName"
                                       placeholder="Nome completo" type="text"
                                       float required validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-address-card" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" id="info_user_cpf" modifier="material" name="fCpf"
                                       type="text"
                                       placeholder="CPF" float validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="" class="list-item__icon icon-spacer"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" id="info_user_rg" modifier="material"
                                       name="fRg"
                                       type="text"
                                       placeholder="RG" float validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-plus-square" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-select style="width: 100%" id="info_user_healthcare" modifier="material" name="fPlano"
                                        class="select"
                                        float>
                                <select class="select-input">
                                    <option value="">Selecione seu plano de saúde</option>
                                    <option value="1">Unimed</option>
                                    <option value="2">Hapvida</option>
                                </select>
                            </ons-select>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-map-marker-alt" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" id="info_user_addr" modifier="material" name="fEnd"
                                       type="text"
                                       placeholder="Endereço Residencial" float validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-mobile-alt" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" id="info_user_ctt_phone" modifier="material" name="fTelCel"
                                       type="text"
                                       placeholder="Telefone Celular" float validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-phone" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" id="info_user_ctt_res" modifier="material"
                                       name="fTelRes" type="text"
                                       placeholder="Telefone Residencial" float validate></ons-input>
                        </ons-list-item>
                        <ons-list-item>
                            <div class="right right-label">
                                <button type="submit" class="button">Salvar</button>
                            </div>
                        </ons-list-item>
                    </ons-col>
                </ons-row>
            </form>
        </ons-card>
        <script>
            ons.getScriptPage().onInit = function () {
                $.get('/mobile/user-profile', {json: true}, function (response) {
                    $.each(response, function (key, value) {
                        if (value !== " " || value !== "" || value !== null) {
                            $("#" + key).val(value);
                        }
                    })
                })
            }
        </script>
    </ons-page>
</template>

<template id="detailsPage.html">
    <ons-page id="detailsPage">
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Busca</ons-back-button>
            </div>
            <div class="center"></div>
        </ons-toolbar>
        <ons-row id="fInformacoes">
        </ons-row>
        <ons-bottom-toolbar onclick="checkDates($('#profid').val())">
            <ons-row>
                <ons class="col"></ons>
                <ons class="col" style="padding-top: 10px">SOLICITAR PROCEDIMENTO</ons>
                <ons class="col"></ons>
            </ons-row>
        </ons-bottom-toolbar>
        <script>
            ons.getScriptPage().onInit = function () {

            }
        </script>
    </ons-page>
</template>

<template id="checkDatePage.html">
    <ons-page id="checkDate">
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Informações</ons-back-button>
            </div>
            <div class="center"></div>
        </ons-toolbar>
        <ons-row>
            <ons-col>
                <ons-card>
                    <div class="title">Selecione uma data abaixo:</div>
                    <div id="callendarArea" style="margin: 10px 0"></div>
                </ons-card>
            </ons-col>
        </ons-row>
    </ons-page>
</template>

<template id="finishAppoint.html">
    <ons-page id="finishAppoint">
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Data</ons-back-button>
            </div>
            <div class="center"></div>
        </ons-toolbar>
        <ons-row>
            <ons-col>
                <ons-card>
                    <div class="title">Preencha as informações para agendamento:</div>
                    <ons-list>
                        <form action="<?= $this->url('application_mobile_user', ["action" => "appoint"]) ?>"
                              method="post" enctype="multipart/form-data" id="form-appoint">
                            <ons-list-header>Data desejada:</ons-list-header>
                            <ons-list-item class="input-items">
                                <div>
                                    <input type="text" class="text-input" name="fDataReq" id="req-date" readonly>
                                </div>
                            </ons-list-item>
                            <ons-list-header hidden>Procedimento desejado:</ons-list-header>
                            <ons-list-item class="input-items" hidden>
                                <div>
                                    <select class="select-input select-input--material" name="fProcdReq" id="req-procd">
                                    </select>
                                </div>
                            </ons-list-item>
                            <ons-list-header>Horário desejado:</ons-list-header>
                            <ons-list-item class="input-items">
                                <div>
                                    <input type="time" class="text-input text-input--material" name="fHoraReq"
                                           id="req-hour">
                                </div>
                            </ons-list-item>
                            <div class="form-params" style="display: none">
                                <input type="text" id="idProf" name="fIdProf">
                                <input type="text" name="mode" value="schedule">
                            </div>
                        </form>
                    </ons-list>
                </ons-card>
            </ons-col>
        </ons-row>
        <ons-bottom-toolbar onclick="sendAppointment()">
            <ons-row>
                <ons class="col"></ons>
                <ons class="col" style="padding-top: 10px">FINALIZAR SOLICITAÇÃO</ons>
                <ons class="col"></ons>
            </ons-row>
        </ons-bottom-toolbar>
        <script>
            ons.getScriptPage().onInit = function () {
                procedureList();
            }
        </script>
    </ons-page>
</template>

<template id="userHistory.html">
    <ons-page>
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Histórico</ons-back-button>
            </div>
            <div class="center"></div>
        </ons-toolbar>

    </ons-page>
</template>

<template id="postponeCustom.html">
    <ons-page id="postponeCustom">
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Solicitações</ons-back-button>
            </div>
            <div class="center">Adiar solicitação</div>
        </ons-toolbar>
        <ons-row>
            <ons-card style="width: 100%">
                <div class="card-title">Informe para quando adiar a solicitação</div>
                <form action="<?= $this->url('application_mobile_user', ['action' => 'appoint']) ?>"
                      method="post" enctype="multipart/form-data" id="presForm">
                    <ons-list-item class="input-items">
                        <div class="left">
                            <ons-icon icon="fa-calendar" class="list-item__icon"></ons-icon>
                        </div>
                        <ons-input style="width: 50%" id="" modifier="material"
                                   name="fDate"
                                   type="date"
                                   float required validate></ons-input>
                    </ons-list-item>
                    <ons-list-item class="input-items">
                        <div class="left">
                            <ons-icon icon="fa-clock" class="list-item__icon"></ons-icon>
                        </div>
                        <ons-input style="width: 40%" id="" modifier="material"
                                   name="fHour"
                                   type="time"
                                   float required validate></ons-input>
                    </ons-list-item>
                    <ons-list-item>
                        <input type="text" name="origin" value="form" hidden>
                        <input type="text" id="solic-id" name="ap_id" hidden>
                        <input type="text" id="solic-op" name="mode" hidden>
                        <div class="right right-label">
                            <button type="submit" class="button">Salvar</button>
                        </div>
                    </ons-list-item>
                </form>
            </ons-card>
        </ons-row>
    </ons-page>
</template>

<?= $this->headScript()->appendFile($this->basePath('plugins/controllers/user-controller.js')) ?>