<ons-navigator swipeable id="mainNavigator" page="mainPage.html"></ons-navigator>

<template id="mainPage.html">
    <ons-page id="mainPage">
        <ons-toolbar>
            <div class="center">SIGAS</div>
        </ons-toolbar>
        <ons-tabbar swipeable position="bottom" id="mainTabbar">
            <ons-tab page="tab1.html" label="Inicio" icon="fa-medkit" active>
            </ons-tab>
            <ons-tab page="tab2.html" label="Histórico" icon="fa-history">
            </ons-tab>
            <ons-tab page="tab3.html" label="Perfil" icon="fa-user-circle">
            </ons-tab>
        </ons-tabbar>
    </ons-page>
</template>

<template id="tab1.html">
    <ons-page id="Tab1">
        <ons-list class="header-custom" style="background-color: #fafafa">
            <ons-list-item class="input-items">
                <ons-search-input id="search-input" maxlength="20" placeholder="Buscar profissional"
                                  style="width: 70%"></ons-search-input>
                <ons-select id="select-input" style="width: 20%; margin-left: 10px">
                    <option value="name">
                        Nome
                    </option>
                    <option value="React">
                        Especialidade
                    </option>
                    <option value="Angular">
                        Endereço
                    </option>
                </ons-select>
            </ons-list-item>
        </ons-list>
        <ons-row>
            <ons-col style="padding: 0">
                <ons-list id="list-profs">
                    <ons-lazy-repeat>
                        <ons-progress-circular indeterminate></ons-progress-circular>
                    </ons-lazy-repeat>
                </ons-list>
            </ons-col>
        </ons-row>
        <style>
            .search-input {
                background-color: transparent;
            }

            .header-custom, .list {
                background-position: bottom;
            }

            .list-item--longdivider {
                background-image: linear-gradient(0deg, #e3e3e3, #e3e3e3 100%);
            }

            ons-progress-circular {
                width: 50px;
                height: 50px;
                position: absolute;
                left: 42%;
                top: 50%;
            }

            .tweet-header {
                width: 100%;
            }
        </style>
        <script>
            ons.getScriptPage().onInit = function () {
                profissionaisList();
            }
        </script>
    </ons-page>
</template>

<template id="tab2.html">
    <ons-page id="Tab2">
        <ons-row>
            <ons-col style="padding: 0 10px">
                <ons-card modifier="material">
                    <div class="title">
                        <h3 class="card__title" style="text-align: center;">Selecione um tipo de registro</h3>
                    </div>
                    <div class="content">
                        <ons-row>
                            <ons-col width="100%">
                                <ons-list style="width: 100%; margin: 0" modifier="inset material" id="fHist">
                                    <ons-lazy-repeat>
                                        <ons-list-item modifier="chevron longdivider"
                                                       onclick="viewHistory(1)" tappable>
                                            Consulta
                                        </ons-list-item>
                                        <ons-list-item modifier="chevron longdivider"
                                                       onclick="viewHistory(2)" tappable>
                                            Exame
                                        </ons-list-item>
                                    </ons-lazy-repeat>
                                </ons-list>
                            </ons-col>
                        </ons-row>
                    </div>
                </ons-card>
            </ons-col>
        </ons-row>
        <script>
            ons.getScriptPage().onInit = function () {
                //$.get('')
            }
        </script>
    </ons-page>
</template>

<template id="tab3.html">
    <ons-page id="Tab3">
        <div id="form-area">
            <div class="content" style="width: 100%">
                <div style="padding: 14px 6px 14px 16px; background-color: aliceblue !important;">
                    <div class="profile_wrapper">
                        <div class="profile_image_wrapper">
                            <img src="assets/img/profile-image-08.png">
                        </div>
                        <div class="profile_info_wrapper">
                            <div class="profile_info_numbers">
                                <div>
                                    <div><?= $this->user['user_information']['user_name'] === null ?
                                            "Não informado" :
                                            $this->user['user_information']['user_name'] ?></div>
                                </div>
                            </div>
                        </div>
                        <div class="profile_info_wrapper">
                            <div class="logoff">
                                <a href="<?= $this->url('logout') ?>">
                                    <ons-toolbar-button style="float: right; ">
                                        <ons-icon icon="ion-log-out"></ons-icon>
                                    </ons-toolbar-button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <ons-card>
                    <div class="title">Dados Pessoais
                        <ons-toolbar-button style="float: right; padding: 0" onclick="editInfo()">
                            <ons-icon icon="ion-edit"></ons-icon>
                        </ons-toolbar-button>
                    </div>

                    <div class="content">
                        <div class="profile_wrapper">
                            <div class="profile_info_wrapper">
                                <div class="profile_info_numbers">
                                    <div>
                                        <div class="profile_info_text">Nome</div>
                                        <div><?= $this->user['user_information']['user_name'] === null ?
                                                "Não informado" :
                                                $this->user['user_information']['user_name'] ?></div>
                                    </div>
                                    <div>
                                        <div class="profile_info_text">CPF</div>
                                        <div><?= $this->user['user_information']['user_cpf'] ?></div>
                                    </div>
                                    <div>
                                        <div class="profile_info_text">Endereço</div>
                                        <div><?= $this->user['user_information']['user_addr'] ?></div>
                                    </div>
                                    <div>
                                        <div class="profile_info_text">Plano de Saúde</div>
                                        <div><?= $this->user['user_information']['user_healthcare'] ?></div>
                                    </div>
                                    <div>
                                        <div class="profile_info_text">Números de contato</div>
                                        <div>Telefone
                                            Celular:<?= $this->user['user_information']['user_ctt_phone'] ?></div>
                                        <div>Telefone
                                            Residencial:<?= $this->user['user_information']['user_ctt_res'] ?></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </ons-card>
                <ons-card>
                    <div class="title">Prescrições disponíveis</div>
                </ons-card>
            </div>
        </div>
        <style type="text/css">
            .profile_wrapper {
                display: inline-flex;
                width: 100%;
            }

            .profile_image_wrapper {
                margin-right: 10px;
                width: 35%;
                position: relative;
            }

            .profile_image_wrapper img {
                width: 100%;
                border-radius: 50%;
                border: 1px solid black;
            }

            .profile_info_wrapper {
                width: 100%;
                text-align: center;
            }

            .profile_extra_wrapper {
                margin: 5px 0 0 0;
                font-size: 14px;
            }

            .profile_info_numbers {
                font-size: 14px;
                display: inline-flex;
                flex-direction: column;
                width: 100%;
            }

            .profile_info_numbers div {
                text-align: left;
                margin: 0 7% 1% 7%;
            }

            .profile_info_text {
                opacity: 0.5;
                margin-top: -5px;
            }

            .profile_info_button {
                height: 25px;
                background: transparent;
                border: 1px solid #e0e0e0;
                border-radius: 7px;
                color: black;
                line-height: 13px;
                font-size: 14px;
                margin-top: 5px;
            }

            .profile_info_button.button--material {
                min-height: 25px;
                line-height: 25px !important;
            }

            .profile_button_bar {
                text-align: center;
                font-size: 26px;
                height: 50px;
                line-height: 40px;
                border-top: 1px solid rgba(187, 187, 187, 0.51)
            }

            .profile_button_bar ons-col {
                width: 25%;
            }

            .post {
                margin: 0px;
                padding: 0px 0px 15px;
                font-size: 14px;
                border-bottom: 1px solid rgba(175, 175, 175, 0.43);
                border-radius: 0;
            }

            .post_title {
                padding-left: 10px;
            }

            .post-caption {
                padding-left: 10px;
            }

            .post-like-info {
                margin-bottom: 5px;
                padding-left: 10px;
            }

            .post-image {
                width: 100%;
            }

            .post-time {
                font-size: 10px;
                opacity: 0.7;
                margin-top: 5px;
                padding-left: 10px;
            }

            .post-like {
                opacity: 0;
                width: 100%;
                position: absolute;
                top: 25%;
                color: white;
                transition: opacity 0.4s;
            }

            .post-button-bar {
                height: 40px;
                padding-left: 0px;
            }

            .post-button {
                font-size: 26px;
                color: #1f1f21;
                line-height: 26px;
            }

            .corner-button {
                color: black;
                font-size: 25px;
                padding-right: 0;
            }

            .like {
                color: red;
            }

            .list-item__thumbnail {
                border-radius: 50%;
            }

            .grid_wrapper {
                width: 33%;
                margin-left: 0.25%;
                margin-right: 0.25%;
            }

            .grid_thumbnail {
                width: 100%;
            }
        </style>
    </ons-page>
</template>

<template id="editInfoForm.html">
    <ons-page id="editInfoForm">
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Perfil</ons-back-button>
            </div>
            <div class="center">
                Editar informações
            </div>
        </ons-toolbar>

        <ons-card>
            <form action="<?= $this->url('application_mobile_user', ["action" => "user-profile"]) ?>" method="post"
                  enctype="multipart/form-data">
                <ons-row>
                    <ons-col width="100%">
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-user" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" modifier="material" id="info_user_name" name="fName"
                                       placeholder="Nome completo" type="text"
                                       float required validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-address-card" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" id="info_user_cpf" modifier="material" name="fCpf"
                                       type="text"
                                       placeholder="CPF" float validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="" class="list-item__icon icon-spacer"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" id="info_user_rg" modifier="material"
                                       name="fRg"
                                       type="text"
                                       placeholder="RG" float validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-plus-square" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-select style="width: 100%" id="info_user_healthcare" modifier="material" name="fPlano"
                                        class="select"
                                        float>
                                <select class="select-input">
                                    <option value="">Selecione seu plano de saúde</option>
                                    <option value="1">Unimed</option>
                                    <option value="2">Hapvida</option>
                                </select>
                            </ons-select>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-map-marker-alt" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" id="info_user_addr" modifier="material" name="fEnd"
                                       type="text"
                                       placeholder="Endereço Residencial" float validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-mobile-alt" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" id="info_user_ctt_phone" modifier="material" name="fTelCel"
                                       type="text"
                                       placeholder="Telefone Celular" float validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-phone" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" id="info_user_ctt_res" modifier="material"
                                       name="fTelRes" type="text"
                                       placeholder="Telefone Residencial" float validate></ons-input>
                        </ons-list-item>
                        <ons-list-item>
                            <div class="right right-label">
                                <button type="submit" class="button">Salvar</button>
                            </div>
                        </ons-list-item>
                    </ons-col>
                </ons-row>
            </form>
        </ons-card>
        <style>
            .list-item__center, .list-item__right {
                background-image: none;
            }

            .icon-spacer::before,
            .icon-blank::before {
                width: 1em;
                content: ' ';
            }
        </style>
        <script>
            ons.getScriptPage().onInit = function () {
                $.get('/mobile/user-profile', {json: true}, function (response) {
                    $.each(response, function (key, value) {
                        if (value !== " " || value !== "" || value !== null) {
                            $("#" + key).val(value);
                        }
                    })
                })
            }
        </script>
    </ons-page>
</template>

<template id="professionalsPage.html">
    <ons-page id="professionalsPage">
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Busca</ons-back-button>
            </div>
            <div class="center">Resultados</div>
        </ons-toolbar>
        <ons-row id="fResultados">
        </ons-row>
    </ons-page>
</template>

<template id="detailsPage.html">
    <ons-page id="detailsPage">
        <ons-toolbar modifier="noshadow" style="background-color: aliceblue !important;">
            <div class="left">
                <ons-back-button>Busca</ons-back-button>
            </div>
            <div class="center"></div>
        </ons-toolbar>
        <ons-row id="fInformacoes">
        </ons-row>
        <ons-bottom-toolbar onclick="checkDates($('#profid').val())">
            <ons-row>
                <ons class="col"></ons>
                <ons class="col" style="padding-top: 10px">SOLICITAR PROCEDIMENTO</ons>
                <ons class="col"></ons>

            </ons-row>
        </ons-bottom-toolbar>
        <style>
            .profile_button_bar_agenda, .profile_button_bar_pac,
            .profile_button_bar_profile {
                text-align: center;
                font-size: 26px;
                /*height: 50px;*/
                line-height: 40px;
                border-top: 1px solid rgba(187, 187, 187, 0.51);
                background-color: #fafafa;
            }

            .profile_button_bar_agenda ons-col {
                width: auto;
            }
            .profile_upper {
                padding: 14px 6px 14px 16px;
                background-color: #fafafa;
            }

            .custom-button {
                color: #c3c3c3;
                width: 100%;
                background-color: #fafafa;
                border-radius: 0;
                box-shadow: none;
            }

            .custom-button.active {
                color: #5fb4f4;
                border-bottom: 2px solid #5fb4f4;
            }
        </style>
        <script>
            ons.getScriptPage().onInit = function () {

            }
        </script>
    </ons-page>
</template>

<template id="checkDatePage.html">
    <ons-page id="checkDate">
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Informações</ons-back-button>
            </div>
            <div class="center"></div>
        </ons-toolbar>
        <ons-row>
            <ons-col>
                <ons-card>
                    <div class="title">Selecione uma data abaixo:</div>
                    <div id="callendarArea" style="margin: 10px 0"></div>
                </ons-card>
            </ons-col>
        </ons-row>
    </ons-page>
</template>

<template id="finishAppoint.html">
    <ons-page id="finishAppoint">
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Data</ons-back-button>
            </div>
            <div class="center"></div>
        </ons-toolbar>
        <ons-row>
            <ons-col>
                <ons-card>
                    <div class="title">Preencha as informações para agendamento:</div>
                    <ons-list>
                        <form action="<?= $this->url('application_mobile_user', ["action" => "save-appoint"]) ?>"
                              method="post" enctype="multipart/form-data" id="form-appoint">
                            <ons-list-header>Data desejada:</ons-list-header>
                            <ons-list-item class="input-items">
                                <div>
                                    <input type="text" class="text-input" name="fDataReq" id="req-date" readonly>
                                </div>
                            </ons-list-item>
                            <ons-list-header>Procedimento desejado:</ons-list-header>
                            <ons-list-item class="input-items">
                                <div>
                                    <select class="select-input select-input--material" name="fProcdReq" id="req-procd">
                                    </select>
                                </div>
                            </ons-list-item>
                            <ons-list-header>Horário desejado:</ons-list-header>
                            <ons-list-item class="input-items">
                                <div>
                                    <input type="time" class="text-input text-input--material" name="fHoraReq"
                                           id="req-hour">
                                </div>
                            </ons-list-item>
                            <div class="form-params" style="display: none">
                                <input type="text" id="idProf" name="fIdProf">
                            </div>
                        </form>
                    </ons-list>
                </ons-card>
            </ons-col>
        </ons-row>
        <ons-bottom-toolbar onclick="sendAppointment()">
            <ons-row>
                <ons class="col"></ons>
                <ons class="col" style="padding-top: 10px">FINALIZAR SOLICITAÇÃO</ons>
                <ons class="col"></ons>
            </ons-row>
        </ons-bottom-toolbar>
        <script>
            ons.getScriptPage().onInit = function () {
                procedureList();
            }
        </script>
    </ons-page>
</template>

<template id="userHistory.html">
    <ons-page>
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Histórico</ons-back-button>
            </div>
            <div class="center"></div>
        </ons-toolbar>
        <ons-row>
            <ons-col>
                <ons-card modifier="material">
                    <div class="title">
                        Registros existentes
                    </div>
                    <div class="content">
                        <ons-row>
                            <ons-col width="100%">
                                <ons-list style="width: 100%; margin: 0" modifier="inset material" id="historyList">
                                    <ons-lazy-repeat>

                                    </ons-lazy-repeat>
                                </ons-list>
                            </ons-col>
                        </ons-row>
                    </div>
                </ons-card>
            </ons-col>
        </ons-row>
    </ons-page>
</template>

<?= $this->headScript()->appendFile($this->basePath('plugins/controllers/user-controller.js')) ?>