<ons-navigator swipeable id="mainNavigator" page="mainPage.html"></ons-navigator>

<template id="mainPage.html">
    <ons-page id="mainPage">
        <ons-toolbar>
            <div class="center">SIGAS</div>
        </ons-toolbar>
        <ons-tabbar swipeable position="bottom" id="mainTabbar">
            <ons-tab page="tab1.html" label="Agenda" icon="fa-calendar" active>
            </ons-tab>
            <ons-tab page="tab2.html" label="Pacientes" icon="fa-user">
            </ons-tab>
            <ons-tab page="tab3.html" label="Perfil" icon="fa-user-md">
            </ons-tab>
            <!--            <ons-tab page="twitter.html" label="Perfil" icon="fa-user-md">-->
            <!--            </ons-tab>-->
            <ons-tab page="profilePage.html" label="Perfil" icon="fa-user-md">
            </ons-tab>
        </ons-tabbar>
        <style>
            .toast{
                opacity: 100;
                background-color: #0f6674;
            }
            .toast-success div{
                background-color: #467447;
            }
            .toast-error div{
                background-color: #a53a39;
            }
        </style>
    </ons-page>
</template>

<template id="tab1.html">
    <ons-page id="Tab1">
        <ons-row class="profile_button_bar_agenda">
            <ons-col>
                <ons-button id="agend" class="custom-button active" onclick="display('agend','agenda',0)">Agenda
                </ons-button>
            </ons-col>
            <ons-col>
                <ons-button id="solic" class="custom-button" icon="fa-checkbox"
                            onclick="display('solic','agenda',1)">Solicitações
                </ons-button>
            </ons-col>
            <ons-col>
                <ons-button id="notif" class="custom-button" onclick="display('notif','agenda',2)">Notificações
                </ons-button>
            </ons-col>
        </ons-row>
        <ons-row>
            <ons-col style="padding: 0">

                <div class="swiper-container-agenda">
                    <div class="swiper-wrapper" style="width: 360px">
                        <div id="agend-view" class="swiper-slide">
                            <div class="calendarArea" style="padding-top: 20px"></div>
                        </div>
                        <div id="solic-view" class="swiper-slide"></div>
                        <div id="notif-view" class="swiper-slide">
                            <ons-card modifier="material">
                                <div class="content">
                                    <ons-row>

                                    </ons-row>
                                </div>
                            </ons-card>
                        </div>
                    </div>
                </div>


            </ons-col>
        </ons-row>
        <style>
            .profile_button_bar_agenda, .profile_button_bar_pac,
            .profile_button_bar_profile {
                text-align: center;
                font-size: 26px;
                /*height: 50px;*/
                line-height: 40px;
                border-top: 1px solid rgba(187, 187, 187, 0.51);
                background-color: #fafafa;
            }

            .profile_button_bar_agenda ons-col {
                width: auto;
            }

            .custom-button {
                color: #c3c3c3;
                width: 100%;
                background-color: #fafafa;
                border-radius: 0;
                box-shadow: none;
            }

            .custom-button.active {
                color: #5fb4f4;
                border-bottom: 2px solid #5fb4f4;
            }

            .swiper-container {
                height: 100%;
            }
        </style>
        <script>
            ons.getScriptPage().onInit = function () {
                initializeCalendar();
                initializeSolics();
            }
        </script>
    </ons-page>
</template>

<template id="tab2.html">
    <ons-page id="Tab2">
        <ons-list class="header-custom" style="background-color: #fafafa">
            <ons-list-item class="input-items">
                <ons-search-input id="search-input" maxlength="20" placeholder="Buscar paciente"
                                  style="width: 70%"></ons-search-input>
                <ons-select id="select-input" style="width: 20%; margin-left: 10px">
                    <option value="name">
                        Nome
                    </option>
                    <option value="React">
                        React
                    </option>
                    <option value="Angular">
                        Angular
                    </option>
                </ons-select>
            </ons-list-item>
        </ons-list>

        <ons-row>
            <ons-col style="padding: 0">
                <ons-card modifier="material" hidden>
                    <div class="title">
                        <h3 class="card__title" style="text-align: center;">Pacientes atendidos</h3>
                    </div>
                    <div class="content">
                        <ons-row>
                            <ons-col width="100%">
                                <ons-list style="width: 100%; margin: 0" modifier="inset material" id="fHistPac">
                                    <ons-lazy-repeat>

                                    </ons-lazy-repeat>
                                </ons-list>
                            </ons-col>
                        </ons-row>
                    </div>
                </ons-card>
                <ons-list id="fHistPac">
                    <ons-lazy-repeat>
                        <ons-progress-circular indeterminate></ons-progress-circular>
                    </ons-lazy-repeat>
                </ons-list>
            </ons-col>
        </ons-row>
        <script>
            ons.getScriptPage().onInit = function () {
                loadPacientes();
            }
        </script>
        <style>
            .search-input {
                background-color: transparent;
            }

            .header-custom, .list {
                background-position: bottom;
            }

            .list-item--longdivider {
                background-image: linear-gradient(0deg, #e3e3e3, #e3e3e3 100%);
            }

            ons-progress-circular {
                width: 50px;
                height: 50px;
                position: absolute;
                left: 42%;
                top: 50%;
            }

            .tweet-header {
                width: 100%;
            }
        </style>
    </ons-page>
</template>

<template id="tab3.html">
    <ons-page id="Tab3">
        <div id="form-area">
            <div class="content" style="width: 100%">
                <div class="profile_upper" style="">
                    <div class="profile_wrapper">
                        <div class="profile_image_wrapper">
                            <img src="http://placekitten.com/g/40/40">
                        </div>
                        <div class="profile_info_wrapper">
                            <div class="profile_info_numbers">
                                <div><?= $this->user['info_user_name'] === null ?
                                        "Não informado" :
                                        $this->user['info_user_name'] ?></div>
                            </div>
                        </div>
                        <div class="profile_info_wrapper">
                            <div class="logoff">
                                <a href="<?= $this->url('logout') ?>">
                                    <ons-toolbar-button style="float: right; ">
                                        <ons-icon icon="ion-log-out"></ons-icon>
                                    </ons-toolbar-button>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div style="padding-top: 5px">Usuário <?= $this->user['pi_confirmed_in'] === null ?
                            "aguardando verificação" :
                            "verificado" ?></div>
                </div>
                <ons-row class="profile_button_bar_profile">
                    <ons-col>
                        <ons-button id="dadpes" class="custom-button active" onclick="display('dadpes', 'profile', 0)">
                            Pessoal
                        </ons-button>
                    </ons-col>
                    <ons-col>
                        <ons-button id="dadprof" class="custom-button" icon="fa-checkbox"
                                    onclick="display('dadprof', 'profile', 1)">Profissional
                        </ons-button>
                    </ons-col>
                    <ons-col>
                        <ons-button id="dadad" class="custom-button" onclick="display('dadad', 'profile', 2)">Adicionais
                        </ons-button>
                    </ons-col>
                </ons-row>
                <ons-row>
                    <div class="swiper-container-profile">
                        <div class="swiper-wrapper" style="width: 360px">
                            <div id="dadpes-view" class="swiper-slide">
                                <div style="height: 200px; padding: 1px 0 0 0;">
                                    <div class="card card--material">
                                        <div class="card__title card--material__title">Dados Pessoais
                                            <ons-toolbar-button style="float: right; padding: 0" onclick="editInfo(0)">
                                                <ons-icon icon="ion-edit"></ons-icon>
                                            </ons-toolbar-button>
                                        </div>
                                        <div class="card__content card--material__content">
                                            <div class="profile_wrapper">
                                                <div class="profile_info_wrapper">
                                                    <div class="profile_info_numbers">
                                                        <div>
                                                            <div class="profile_info_text">Nome</div>
                                                            <div>
                                                                <?= $this->user['info_user_name'] ?>
                                                            </div>
                                                        </div>
                                                        <div>
                                                            <div class="profile_info_text">CPF</div>
                                                            <div><?= $this->user['info_user_cpf'] ?></div>
                                                        </div>
                                                        <div>
                                                            <div class="profile_info_text">RG</div>
                                                            <div><?= $this->user['info_user_rg'] ?></div>
                                                        </div>
                                                        <div>
                                                            <div class="profile_info_text">Status do Profissional</div>
                                                            <div>Cadastro solicitado
                                                                em: <?= date("d/m/Y", strtotime($this->user['pi_solicited_in'])) ?></div>
                                                            <div>Cadastro verificado
                                                                em: <?= $this->user['pi_confirmed_in'] === null ? "Aguardando verificação" : date("d/m/Y", strtotime($this->user['pi_confirmed_in'])) ?></div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div id="dadprof-view" class="swiper-slide">
                                <div style="height: 200px; padding: 1px 0 0 0;">
                                    <div class="card card--material">
                                        <div class="card__title card--material__title">Dados Profissionais
                                            <ons-toolbar-button style="float: right; padding: 0" onclick="editInfo(1)">
                                                <ons-icon icon="ion-edit"></ons-icon>
                                            </ons-toolbar-button>
                                        </div>
                                        <div class="card__content card--material__content">
                                            <div class="profile_wrapper">
                                                <div class="profile_info_wrapper">
                                                    <div class="profile_info_numbers">
                                                        <div>
                                                            <div class="profile_info_text">Especialidade</div>
                                                            <div>
                                                                <?= $this->user['pi_confirmed_in'] === null ?
                                                                    "Aguardando validação" :
                                                                    $this->user['esp_desc_especialidade'] ?>
                                                            </div>
                                                        </div>
                                                        <div>
                                                            <div class="profile_info_text">Conselho</div>
                                                            <div><?= $this->user['pi_cons_registry'] ?>
                                                                - <?= $this->user['pc_desc_conselho'] ?></div>
                                                        </div>
                                                        <div>
                                                            <div class="profile_info_text">Endereço</div>
                                                            <div><?= $this->user['info_user_addr'] ?></div>
                                                        </div>
                                                        <div>
                                                            <div class="profile_info_text">Números de contato</div>
                                                            <div>Telefone
                                                                Celular:<?= $this->user['info_user_ctt_phone'] ?></div>
                                                            <div>Telefone
                                                                Residencial:<?= $this->user['info_user_ctt_res'] ?></div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div id="dadad-view" class="swiper-slide"></div>
                        </div>
                    </div>
                </ons-row>
            </div>
        </div>
        <style type="text/css">
            .profile_upper {
                padding: 14px 6px 14px 16px;
                background-color: #fafafa;
            }

            .profile_wrapper {
                display: inline-flex;
                width: 100%;
            }

            .profile_image_wrapper {
                margin-right: 10px;
                width: 35%;
                position: relative;
            }

            .profile_image_wrapper img {
                width: 100%;
                border-radius: 50%;
                border: 1px solid black;
            }

            .profile_info_wrapper {
                width: 100%;
                text-align: center;
            }

            .profile_extra_wrapper {
                margin: 5px 0 0 0;
                font-size: 14px;
            }

            .profile_info_numbers {
                font-size: 14px;
                display: inline-flex;
                flex-direction: column;
                width: 100%;
            }

            .profile_info_numbers div {
                text-align: left;
                margin: 0 7% 1% 7%;
            }

            .profile_info_text {
                opacity: 0.5;
                margin-top: -5px;
            }

            .profile_info_button {
                height: 25px;
                background: transparent;
                border: 1px solid #e0e0e0;
                border-radius: 7px;
                color: black;
                line-height: 13px;
                font-size: 14px;
                margin-top: 5px;
            }

            .profile_info_button.button--material {
                min-height: 25px;
                line-height: 25px !important;
            }

            .profile_button_bar {
                text-align: center;
                font-size: 26px;
                height: 50px;
                line-height: 40px;
                border-top: 1px solid rgba(187, 187, 187, 0.51)
            }

            .profile_button_bar ons-col {
                width: 25%;
            }

            .post {
                margin: 0px;
                padding: 0px 0px 15px;
                font-size: 14px;
                border-bottom: 1px solid rgba(175, 175, 175, 0.43);
                border-radius: 0;
            }

            .post_title {
                padding-left: 10px;
            }

            .post-caption {
                padding-left: 10px;
            }

            .post-like-info {
                margin-bottom: 5px;
                padding-left: 10px;
            }

            .post-image {
                width: 100%;
            }

            .post-time {
                font-size: 10px;
                opacity: 0.7;
                margin-top: 5px;
                padding-left: 10px;
            }

            .post-like {
                opacity: 0;
                width: 100%;
                position: absolute;
                top: 25%;
                color: white;
                transition: opacity 0.4s;
            }

            .post-button-bar {
                height: 40px;
                padding-left: 0px;
            }

            .post-button {
                font-size: 26px;
                color: #1f1f21;
                line-height: 26px;
            }

            .corner-button {
                color: black;
                font-size: 25px;
                padding-right: 0;
            }

            .like {
                color: red;
            }

            .list-item__thumbnail {
                border-radius: 50%;
            }

            .grid_wrapper {
                width: 33%;
                margin-left: 0.25%;
                margin-right: 0.25%;
            }

            .grid_thumbnail {
                width: 100%;
            }
        </style>
    </ons-page>
</template>

<template id="editInfoPesForm.html">
    <ons-page id="editInfoPesForm">
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Perfil</ons-back-button>
            </div>
            <div class="center">
                Editar informações
            </div>
        </ons-toolbar>

        <ons-card>
            <form action="<?= $this->url('application_mobile_prof', ["action" => "user-profile"]) ?>" method="post"
                  enctype="multipart/form-data">
                <ons-row>
                    <ons-col width="100%">
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-user" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" modifier="material" id="info_user_name" name="fName"
                                       placeholder="Nome completo" type="text"
                                       float required validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-address-card" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" id="info_user_cpf" modifier="material" name="fCpf"
                                       type="text"
                                       placeholder="CPF" float validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="" class="list-item__icon icon-spacer"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" id="info_user_rg" modifier="material"
                                       name="fRg"
                                       type="text"
                                       placeholder="RG" float validate></ons-input>
                        </ons-list-item>
                        <ons-list-item>
                            <div class="right right-label">
                                <button type="submit" class="button">Salvar</button>
                            </div>
                        </ons-list-item>
                    </ons-col>
                </ons-row>
            </form>
        </ons-card>
        <style>
            .list-item__center, .list-item__right {
                background-image: none;
            }

            .icon-spacer::before,
            .icon-blank::before {
                width: 1em;
                content: ' ';
            }
        </style>
        <script>
            ons.getScriptPage().onInit = function () {
                $.get('/mobile/user-profile', {json: true}, function (response) {
                    $.each(response, function (key, value) {
                        if (value !== " " || value !== "" || value !== null) {
                            $("#" + key).val(value);
                        }
                    })
                })
            }
        </script>
    </ons-page>
</template>

<template id="editInfoProfForm.html">
    <ons-page id="editInfoProfForm">
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Perfil</ons-back-button>
            </div>
            <div class="center">
                Editar informações profissionais
            </div>
        </ons-toolbar>
        <ons-card>
            <ons-row>
                <ons-col>
                    <form action="<?= $this->url('application_mobile_prof', ['action' => 'get-profile']) ?>"
                          method="post" enctype="multipart/form-data">
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-plus-square" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-select style="width: 100%" id="pi_cons_name" modifier="material" name="fCons"
                                        class="select"
                                        float>
                                <select class="select-input">
                                    <?php foreach ($this->cons as $con): ?>
                                        <option value="<?= $con['c_id'] ?>"><?= $con['c_desc_conselho'] ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </ons-select>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-address-card" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" id="pi_especiality_solicited" modifier="material"
                                       name="fEspSoc"
                                       type="text"
                                       placeholder="Especialidade informada" float validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-address-card" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" id="pi_cons_registry" modifier="material" name="fNumIns"
                                       type="text"
                                       placeholder="Número de inscrição" float validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items end">
                            <div class="left">
                                <ons-icon icon="fa-map-marker-alt" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 80%" id="info_user_addr" modifier="material" name="fEnd[]"
                                       type="text"
                                       placeholder="Endereço Principal" float validate></ons-input>
                            <button type="button" class="fab fab--mini" onclick="addAddress()"><i
                                        class="zmdi zmdi-plus"></i></button>
                        </ons-list-item>
                        <div class="addr-area">

                        </div>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-mobile-alt" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" id="info_user_ctt_phone" modifier="material" name="fTelCel"
                                       type="text"
                                       placeholder="Telefone Celular" float validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-phone" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" id="info_user_ctt_res" modifier="material"
                                       name="fTelRes" type="text"
                                       placeholder="Telefone Clinica" float validate></ons-input>
                        </ons-list-item>
                        <ons-list-item>
                            <div class="right right-label">
                                <button type="submit" class="button">Salvar</button>
                            </div>
                        </ons-list-item>
                    </form>
                </ons-col>
            </ons-row>
        </ons-card>
        <style>
            .list-item__center, .list-item__right {
                background-image: none;
            }

            .icon-spacer::before,
            .icon-blank::before {
                width: 1em;
                content: ' ';
            }
        </style>
        <script>
            ons.getScriptPage().onInit = function () {

            }
        </script>
    </ons-page>
</template>

<template id="checkDatePage.html">
    <ons-page id="checkDate">
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Informações</ons-back-button>
            </div>
            <div class="center"></div>
        </ons-toolbar>
        <ons-row>
            <ons-col>
                <ons-card>
                    <div class="title">Selecione uma data abaixo:</div>
                    <div id="callendarArea" style="margin: 10px 0"></div>
                </ons-card>
            </ons-col>
        </ons-row>
    </ons-page>
</template>

<template id="pacProfile.html">
    <ons-page>
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Pacientes</ons-back-button>
            </div>
            <div class="center"></div>
        </ons-toolbar>
        <div id="form-area">
            <div class="content" style="width: 100%">
                <div class="profile_upper">
                    <div class="profile_wrapper">
                        <div class="profile_image_wrapper">
                            <img src="http://placekitten.com/g/40/40">
                        </div>
                        <div class="profile_info_wrapper">
                            <div class="profile_info_numbers">
                                <div>
                                    <div></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <ons-row class="profile_button_bar_pac">
                    <ons-col>
                        <ons-button id="infos" class="custom-button active" onclick="display('infos','pac',0)">
                            Informações
                        </ons-button>
                    </ons-col>
                    <ons-col>
                        <ons-button id="histo" class="custom-button" icon="fa-checkbox"
                                    onclick="display('histo', 'pac',1)">Histórico
                        </ons-button>
                    </ons-col>
                </ons-row>
                <ons-row>
                    <div class="swiper-container-pac">
                        <div class="swiper-wrapper" style="width: 360px">
                            <div class="swiper-slide" id="infos-view">
                                <ons-card>
                                    <div class="title">Informações do paciente</div>
                                    <div class="content">
                                        <div class="profile_wrapper">
                                            <div class="profile_info_wrapper">
                                                <div class="profile_info_numbers">
                                                    <div>
                                                        <div class="profile_info_text">Nome</div>
                                                        <div id="u_name"></div>
                                                    </div>
                                                    <div>
                                                        <div class="profile_info_text">CPF</div>
                                                        <div id="u_cpf"></div>
                                                    </div>
                                                    <div>
                                                        <div class="profile_info_text">Plano de Saúde</div>
                                                        <div id="u_healthcare"></div>
                                                    </div>
                                                    <div>
                                                        <div class="profile_info_text">Números de contato</div>
                                                        <div id="u_ctt_phone">Telefone
                                                            Celular:
                                                        </div>
                                                        <div id="u_ctt_res">Telefone
                                                            Residencial:
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </ons-card>
                            </div>
                            <div class="swiper-slide" id="histo-view">
                                <ons-card>
                                    <div class="title">Registros no histórico</div>
                                    <div class="content">
                                        <ons-row>
                                            <ons-col width="100%">
                                                <ons-list style="width: 100%; margin: 0" modifier="inset material" id="fRegPac">
                                                    <ons-lazy-repeat>

                                                    </ons-lazy-repeat>
                                                </ons-list>
                                            </ons-col>
                                        </ons-row>
                                    </div>
                                </ons-card>
                            </div>
                        </div>
                    </div>
                </ons-row>



            </div>
        </div>
        <ons-speed-dial position="bottom right" direction="up">
            <ons-fab>
                <ons-icon icon="fa-plus"></ons-icon>
            </ons-fab>
            <ons-speed-dial-item onclick="insertHistoric(0)">
                <ons-icon icon="fa-pills"></ons-icon>
                <div>Prescrição</div>
            </ons-speed-dial-item>
            <ons-speed-dial-item onclick="insertHistoric(1)">
                <ons-icon icon="fa-stethoscope"></ons-icon>
                <div class="speed-dial-text">Exame</div>
            </ons-speed-dial-item>
            <ons-speed-dial-item onclick="insertHistoric(2)">
                <ons-icon icon="fa-user-md"></ons-icon>
                <div class="speed-dial-text">Procedimento</div>
            </ons-speed-dial-item>
            <ons-speed-dial-item onclick="insertHistoric(3)">
                <ons-icon icon="fa-notes-medical"></ons-icon>
                <div class="speed-dial-text">Notas</div>
            </ons-speed-dial-item>
        </ons-speed-dial>
        <style>
            ons-speed-dial-item.speed-dial__item {
                /*width: 150px;*/
                /*border-radius: 10%;*/
            }

            .speed-dial-text {
                font-size: 14pt;
                line-height: 20px;
            }

            .speed-dial__item div {
                position: absolute;
                background: rgba(0, 0, 0, 0);
                font-size: 15px;
                padding: 0 5px;
                border-radius: 10px;
                top: 3px;
                right: 45px;
                color: #5fb4f4;
                width: 100px;
                text-align: right;
            }

            .speed-dial__item {
                overflow: visible !important;
            }

            ons-speed-dial:before {
                content: '';
                display: block;
                position: fixed;
                visibility: hidden;
                top: 0;
                left: 0;
                bottom: 0;
                right: 0;
                background: rgba(0, 0, 0, 0.2);
                opacity: 0;
                transition: opacity 0.2s ease-in-out;
            }

            ons-speed-dial.open:before {
                opacity: 1;
                visibility: visible;
            }
        </style>
    </ons-page>
</template>

<template id="addHistoric.html">
    <ons-page id="add-Historic">
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Paciente</ons-back-button>
            </div>
            <div class="center">Inserir no histórico</div>
        </ons-toolbar>
        <ons-row>
            <ons-col>
                <ons-card>
                    <div class="title">Preencha as informações necessárias:</div>
                    <div id="presArea" style="display: none">
                        <form action="<?= $this->url('application_mobile_prof', ['action' => 'save-historic']) ?>"
                              method="post" enctype="multipart/form-data" id="presForm">
                            <ons-list-item class="input-items">
                                <div class="left">
                                    <ons-icon icon="fa-pills" class="list-item__icon"></ons-icon>
                                </div>
                                <ons-input style="width: 100%" id="" modifier="material"
                                           name="fMedic[]"
                                           type="text"
                                           placeholder="Medicamento" float validate></ons-input>
                            </ons-list-item>
                            <ons-list-item class="input-items">
                                <div class="left">
                                    <ons-icon icon="fa-prescription-bottle" class="list-item__icon"></ons-icon>
                                </div>
                                <ons-input style="width: 100%" id="" modifier="material"
                                           name="fDose[]"
                                           type="text"
                                           placeholder="Dosagem" float validate></ons-input>
                            </ons-list-item>
                            <ons-list-item class="input-items">
                                <div class="left">
                                    <ons-icon icon="fa-clock" class="list-item__icon"></ons-icon>
                                </div>
                                <textarea class="textarea" name="fPoso[]" rows="3" placeholder="Posologia"
                                          style="width: 100%"></textarea>

                            </ons-list-item>
                            <div id="prescList" style="display: none;">
                                <div class="left">
                                    Nesta prescrição:
                                </div>
                            </div>
                            <ons-list-item>
                                <div class="left left-label">
                                    <button type="button" class="button" onclick="addRem()">+</button>
                                </div>
                                <div class="right right-label">
                                    <button type="submit" class="button">Salvar</button>
                                </div>
                            </ons-list-item>

                            <div id="addPrescArea" hidden>

                            </div>
                        </form>
                    </div>
                    <div id="rxArea" style="display: none">
                        <form action="<?= $this->url('application_mobile_prof', ['action' => 'save-historic']) ?>"
                              method="post" enctype="multipart/form-data" id="rxForm">
                            <ons-list-item class="input-items">
                                <div class="left">
                                    <ons-icon icon="fa-file-prescription" class="list-item__icon"></ons-icon>
                                </div>
                                <ons-input style="width: 100%" id="" modifier="material"
                                           name="fExam"
                                           type="text"
                                           placeholder="Exame" float validate></ons-input>
                            </ons-list-item>
                            <ons-list-item class="input-items">
                                <div class="left">
                                    <ons-icon icon="fa-barcode" class="list-item__icon"></ons-icon>
                                </div>
                                <ons-input style="width: 100%" id="" modifier="material"
                                           name="fCodigo"
                                           type="text"
                                           placeholder="Código do Exame" float validate></ons-input>
                            </ons-list-item>
                            <ons-list-item class="input-items">
                                <div class="left">
                                    <ons-icon icon="fa-info" class="list-item__icon"></ons-icon>
                                </div>
                                <textarea class="textarea" name="fDesc" rows="3" placeholder="Mais informações"
                                          style="width: 100%"></textarea>

                            </ons-list-item>
                            <ons-list-item>
                                <div class="right right-label">
                                    <button type="submit" class="button">Salvar</button>
                                </div>
                            </ons-list-item>
                            <div id="rxInfos" hidden>

                            </div>
                        </form>
                    </div>
                    <div id="remArea" style="display: none">
                        <form action="<?= $this->url('application_mobile_prof', ['action' => 'save-historic']) ?>"
                              method="post" enctype="multipart/form-data" id="remForm">
                            <ons-list-item class="input-items">
                                <div class="left">
                                    <ons-icon icon="fa-stethoscope" class="list-item__icon"></ons-icon>
                                </div>
                                <ons-input style="width: 100%" id="" modifier="material"
                                           name="fExam"
                                           type="text"
                                           placeholder="Procedimento" float validate></ons-input>
                            </ons-list-item>

                            <ons-list-item class="input-items">
                                <div class="left">
                                    <ons-icon icon="fa-file-alt" class="list-item__icon"></ons-icon>
                                </div>
                                <ons-select style="width: 100%" id="pi_cons_name" modifier="material" name="fCons"
                                            class="select"
                                            float>
                                    <select class="select-input">
                                        <?php foreach ($this->proceds as $proc): ?>
                                            <option value="<?= $proc['p_id_procedure'] ?>"><?= $proc['procedure_description'] ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </ons-select>
<!--                                <ons-input style="width: 100%" id="" modifier="material"-->
<!--                                           name="fCodigo"-->
<!--                                           type="text"-->
<!--                                           placeholder="Tipo de procedimento" float validate></ons-input>-->
                            </ons-list-item>
                            <ons-list-item class="input-items">
                                <div class="left">
                                    <ons-icon icon="fa-calendar" class="list-item__icon"></ons-icon>
                                </div>
                                <ons-input style="width: 100%" id="" modifier="material"
                                           name="fCodigo"
                                           type="date"
                                           placeholder="" float validate></ons-input>
                            </ons-list-item>
                            <ons-list-item class="input-items">
                                <div class="left">
                                    <ons-icon icon="fa-info" class="list-item__icon"></ons-icon>
                                </div>
                                <textarea class="textarea" name="fDesc" rows="3" placeholder="Mais informações"
                                          style="width: 100%"></textarea>
                            </ons-list-item>
                            <ons-list-item>
                                <div class="right right-label">
                                    <button type="submit" class="button">Salvar</button>
                                </div>
                            </ons-list-item>
                            <div id="remInfos" hidden>

                            </div>
                        </form>
                    </div>
                    <div id="noteArea" style="display: none">
                        <form action="<?= $this->url('application_mobile_prof', ['action' => 'save-historic']) ?>"
                              method="post" enctype="multipart/form-data" id="noteForm">
                            <ons-list-item class="input-items">
                                <div class="left">
                                    <ons-icon icon="fa-info" class="list-item__icon"></ons-icon>
                                </div>
                                <textarea class="textarea" name="fNotes" rows="4" placeholder="Descreva a nota"
                                          style="width: 100%"></textarea>
                            </ons-list-item>
                            <ons-list-item>
                                <div class="right right-label">
                                    <button type="submit" class="button">Salvar</button>
                                </div>
                            </ons-list-item>
                            <div id="remInfos" hidden>

                            </div>
                        </form>
                    </div>
                </ons-card>
            </ons-col>
        </ons-row>
        <style>
            .list-item__center, .list-item__right {
                background-image: none;
            }

            .toast {
                background-color: #0f6674;
                opacity: 100;
            }

            p {
                width: 100%;
            }
        </style>
    </ons-page>
</template>

<template id="twitter.html">
    <ons-page id="home-page">
        <ons-pull-hook>
            <ons-icon size="30px" spin icon="md-spinner"></ons-icon>
        </ons-pull-hook>
        <ons-list>

            <ons-list-item modifier="longdivider">
                <div class="left">
                    <img class="list-item__thumbnail" src="http://placekitten.com/g/50/50">
                </div>
                <div class="center">
                    <div class="tweet-header">
                        <span class="list-item__title"><b>Cute Kitty 2</b></span>
                        <span class="list-item__subtitle"><span
                                    class="username">@cKitty2</span>&nbsp;&#8231;&nbsp;2d</span>
                        <ons-button class="option-arrow" modifier="quiet" onclick="ons.openActionSheet({
              cancelable: true,
              buttons: [
                'Share Tweet via...',
                'Add to Moment',
                'I don\'t like this Tweet',
                'Unfollow @cKitty2',
                'Mute @cKitty2',
                'Block @cKitty2',
                'Report Tweet',
                {
                  label: 'Cancel',
                  icon: 'md-close'
                }
              ]
            })">
                            <ons-icon icon="ion-arrow-down-b"></ons-icon>
                        </ons-button>
                    </div>
                    <span class="list-item__content">
            Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
            <img src="http://placekitten.com/g/200/200" alt="PostImage">
          </span>
                    <ons-row class="option-buttons">
                        <ons-col>
                            <ons-button modifier="quiet">
                                <ons-icon icon="ion-reply"></ons-icon>
                                <span class="reaction-no">2</span>
                            </ons-button>
                        </ons-col>
                        <ons-col>
                            <ons-button modifier="quiet">
                                <ons-icon icon="retweet"></ons-icon>
                                <span class="reaction-no">4</span>
                            </ons-button>
                        </ons-col>
                        <ons-col>
                            <ons-button modifier="quiet">
                                <ons-icon icon="ion-heart"></ons-icon>
                                <span class="reaction-no">6</span>
                            </ons-button>
                        </ons-col>
                        <ons-col>
                            <ons-button modifier="quiet">
                                <ons-icon icon="ion-email"></ons-icon>
                            </ons-button>
                        </ons-col>
                    </ons-row>
                </div>
            </ons-list-item>
            <ons-list-item modifier="longdivider">
                <div class="left">
                    <img class="list-item__thumbnail" src="http://placekitten.com/g/60/60">
                </div>
                <div class="center">
                    <div class="tweet-header">
                        <span class="list-item__title"><b>Cute Kitty 3</b></span>
                        <span class="list-item__subtitle"><span
                                    class="username">@cKitty3</span>&nbsp;&#8231;&nbsp;3d</span>
                        <ons-button class="option-arrow" modifier="quiet" onclick="ons.openActionSheet({
              cancelable: true,
              buttons: [
                'Share Tweet via...',
                'Add to Moment',
                'I don\'t like this Tweet',
                'Unfollow @cKitty3',
                'Mute @cKitty3',
                'Block @cKitty3',
                'Report Tweet',
                {
                  label: 'Cancel',
                  icon: 'md-close'
                }
              ]
            })">
                            <ons-icon icon="ion-arrow-down-b"></ons-icon>
                        </ons-button>
                    </div>
                    <span class="list-item__content">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</span>
                    <ons-row class="option-buttons">
                        <ons-col>
                            <ons-button modifier="quiet">
                                <ons-icon icon="ion-reply"></ons-icon>
                                <span class="reaction-no">3</span>
                            </ons-button>
                        </ons-col>
                        <ons-col>
                            <ons-button modifier="quiet">
                                <ons-icon icon="retweet"></ons-icon>
                                <span class="reaction-no">6</span>
                            </ons-button>
                        </ons-col>
                        <ons-col>
                            <ons-button modifier="quiet">
                                <ons-icon icon="ion-heart"></ons-icon>
                                <span class="reaction-no">9</span>
                            </ons-button>
                        </ons-col>
                        <ons-col>
                            <ons-button modifier="quiet">
                                <ons-icon icon="ion-email"></ons-icon>
                            </ons-button>
                        </ons-col>
                    </ons-row>
                </div>
            </ons-list-item>

            <div style="text-align: center; margin-bottom: 30px">
                <ons-icon size="30px" spin icon="md-spinner"></ons-icon>
            </div>
        </ons-list>


    </ons-page>
</template>

<template id="profilePage.html">
    <ons-page class="main_pages" id="profile-page">
        <ons-toolbar>
            <div class="left">
                <ons-toolbar-button>
                    <ons-icon icon="ion-person-add"></ons-icon>
                </ons-toolbar-button>
            </div>
            <div class="center">david_graham</div>
            <div class="right">
                <ons-toolbar-button>
                    <ons-icon icon="ion-gear-a"></ons-icon>
                </ons-toolbar-button>
            </div>
        </ons-toolbar>

        <div class="content" style="background-color: white !important">

            <!-- The content of the profile page is organized into several parts -->

            <!-- The first part contains the user's profile picture on the left, and info about the number of posts, following and followed users on the right side of the screen -->

            <div style="padding: 14px 6px 14px 16px;">
                <div class="profile_wrapper">
                    <div class="profile_image_wrapper">
                        <ons-icon size="24px" icon="ion-ios-plus"></ons-icon>
                        <img src="assets/img/profile-image-08.png">
                    </div>
                    <div class="profile_info_wrapper">
                        <div class="profile_info_numbers">
                            <div>
                                <div>3</div>
                                <div class="profile_info_text">Posts</div>
                            </div>
                            <div>
                                <div>150</div>
                                <div class="profile_info_text">Followers</div>
                            </div>
                            <div>
                                <div>150</div>
                                <div class="profile_info_text">Following</div>
                            </div>
                        </div>
                        <div>
                            <ons-button class="profile_info_button" id="edit_button" modifier="large">Edit Your
                                Profile
                            </ons-button>
                        </div>
                    </div>
                </div>
                <div><p class="profile_extra_wrapper"> David Graham</p></div>
            </div>


            <!-- The next part contains the buttons bar. Since we don't want any pressing effect, the buttons are implemented as simple icons instead -->

            <ons-row class="profile_button_bar">
                <ons-col>
                    <ons-icon id="grid" icon="ion-grid" style="color: #5fb4f4" onclick="display('grid')"></ons-icon>
                </ons-col>
                <ons-col>
                    <ons-icon id="list" icon="md-format-list-bulleted" onclick="display('list')"></ons-icon>
                </ons-col>
                <ons-col>
                    <ons-icon icon="ion-ios-pricetag-outline"></ons-icon>
                </ons-col>
                <ons-col>
                    <ons-icon class="bookmark" icon="fa-bookmark-o"></ons-icon>
                </ons-col>
            </ons-row>

            <!-- The last part is cosnisted of two <div> elements that display the posts of the users in two ways. The first one displays them as posts, just like the home screen, the other as a grid, similar to the search page -->

            <div id="list_view" style="display: none;">
                <ons-card class="post">
                    <ons-list-item class="post_title">
                        <div class="left">
                            <img class="list-item__thumbnail" src="assets/img/profile-image-03.png">
                        </div>
                        <div class="center">
                            <div class="list-item__title"><b>david_graham</b></div>
                            <div class="list-item__subtitle" style="font-size: 12px">Fushimi Inari Shrine, Kyoto</div>
                        </div>
                        <div class="right">
                            <ons-button class="corner-button" modifier="quiet">
                                <ons-icon icon="ion-ios-more,material:ion-android-more-vertical"></ons-icon>
                            </ons-button>
                        </div>
                    </ons-list-item>

                    <div style="text-align: center; position: relative;" ondblclick="like('01')">
                        <ons-icon size="150px" id="post-like-01" class="post-like" icon="ion-ios-heart"></ons-icon>
                        <img class="post-image" src="assets/img/post-01.jpg">
                    </div>

                    <ons-list-item class="post-button-bar" modifier="nodivider">
                        <div class="center" style="padding-top: 0px">
                            <ons-button class="post-button" modifier="quiet" onclick="like('01')">
                                <ons-icon id="button-post-like-01" icon="ion-ios-heart-outline"></ons-icon>
                            </ons-button>
                            <ons-button class="post-button" modifier="quiet">
                                <ons-icon icon="ion-ios-chatbubble-outline"></ons-icon>
                            </ons-button>
                            <ons-button class="post-button" modifier="quiet">
                                <ons-icon icon="ion-ios-paperplane-outline"></ons-icon>
                            </ons-button>
                        </div>
                        <div class="right corner-button bookmark">
                            <ons-button class="post-button" modifier="quiet">
                                <ons-icon icon="md-bookmark-outline"></ons-icon>
                            </ons-button>
                        </div>
                    </ons-list-item>

                    <div class="post-like-info"><b>someone_one</b> and 24 other liked this.</div>
                    <div class="post-caption"><b>david_graham</b> beautiful kyoto #kyoto #fushimiinarishirine</div>
                    <div class="post-time">1 HOUR AGO</div>
                </ons-card>

                <ons-card class="post">
                    <ons-list-item class="post_title">
                        <div class="left">
                            <img class="list-item__thumbnail" src="assets/img/profile-image-08.png">
                        </div>
                        <div class="center">
                            <div class="list-item__title"><b>david_graham</b></div>
                            <div class="list-item__subtitle" style="font-size: 12px">Kinkakuji Temple, Kyoto</div>
                        </div>
                        <div class="right corner-button">
                            <ons-toolbar-button>
                                <ons-icon icon="ion-ios-more,material:ion-android-more-vertical"></ons-icon>
                            </ons-toolbar-button>
                        </div>
                    </ons-list-item>

                    <div style="text-align: center; position: relative;" ondblclick="like('02')">
                        <ons-icon size="150px" id="post-like-02" class="post-like" icon="ion-ios-heart"></ons-icon>
                        <img class="post-image" src="assets/img/post-02.jpg">
                    </div>

                    <ons-list-item class="post-button-bar" modifier="nodivider">
                        <div class="center" style="padding-top: 0px">
                            <ons-button class="post-button" modifier="quiet" onclick="like('02')">
                                <ons-icon id="button-post-like-02" icon="ion-ios-heart-outline"></ons-icon>
                            </ons-button>
                            <ons-button class="post-button" modifier="quiet">
                                <ons-icon icon="ion-ios-chatbubble-outline"></ons-icon>
                            </ons-button>
                            <ons-button class="post-button" modifier="quiet">
                                <ons-icon icon="ion-ios-paperplane-outline"></ons-icon>
                            </ons-button>
                        </div>
                        <div class="right corner-button bookmark">
                            <ons-button class="post-button" modifier="quiet">
                                <ons-icon icon="md-bookmark-outline"></ons-icon>
                            </ons-button>
                        </div>
                    </ons-list-item>

                    <div class="post-like-info"><b>someone_one</b> and 24 other liked this.</div>
                    <div class="post-caption"><b>david_graham</b> Golden Temple ^_^ #kyoto #goldentemple</div>
                    <div class="post-time">1 HOUR AGO</div>
                </ons-card>

                <ons-card class="post">
                    <ons-list-item class="post_title">
                        <div class="left">
                            <img class="list-item__thumbnail" src="assets/img/profile-image-02.png">
                        </div>
                        <div class="center">
                            <div class="list-item__title"><b>david_graham</b></div>
                            <div class="list-item__subtitle" style="font-size: 12px">Tokyo</div>
                        </div>
                        <div class="right">
                            <ons-button class="corner-button" modifier="quiet">
                                <ons-icon icon="ion-ios-more,material:ion-android-more-vertical"></ons-icon>
                            </ons-button>
                        </div>
                    </ons-list-item>

                    <div style="text-align: center; position: relative;" ondblclick="like('03')">
                        <ons-icon size="150px" id="post-like-03" class="post-like" icon="ion-ios-heart"></ons-icon>
                        <img class="post-image" src="assets/img/post-03.jpg">
                    </div>

                    <ons-list-item class="post-button-bar" modifier="nodivider">
                        <div class="center" style="padding-top: 0px">
                            <ons-button class="post-button" modifier="quiet" onclick="like('03')">
                                <ons-icon id="button-post-like-03" icon="ion-ios-heart-outline"></ons-icon>
                            </ons-button>
                            <ons-button class="post-button" modifier="quiet">
                                <ons-icon icon="ion-ios-chatbubble-outline"></ons-icon>
                            </ons-button>
                            <ons-button class="post-button" modifier="quiet">
                                <ons-icon icon="ion-ios-paperplane-outline"></ons-icon>
                            </ons-button>
                        </div>
                        <div class="right corner-button bookmark">
                            <ons-button class="post-button" modifier="quiet">
                                <ons-icon icon="md-bookmark-outline"></ons-icon>
                            </ons-button>
                        </div>
                    </ons-list-item>

                    <div class="post-like-info"><b>someone_one</b> and 24 other liked this.</div>
                    <div class="post-caption"><b>david_graham</b> The harmony sakura brings #sakura #happy #harmony
                        #love
                    </div>
                    <div class="post-time">1 HOUR AGO</div>
                </ons-card>
            </div>

            <div id="grid_view">
                <ons-row>
                    <ons-col class="grid_wrapper">
                        <img class="grid_thumbnail" src="assets/img/post-01.jpg">
                    </ons-col>

                    <ons-col class="grid_wrapper">
                        <img class="grid_thumbnail" src="assets/img/post-02.jpg">
                    </ons-col>

                    <ons-col class="grid_wrapper">
                        <img class="grid_thumbnail" src="assets/img/post-03.jpg">
                    </ons-col>
                </ons-row>
            </div>
        </div>


    </ons-page>
</template>

<?= $this->headScript()->appendFile($this->basePath('plugins/controllers/professional-controller.js')) ?>

<style>
    .fc-next-button, .fc-prev-button, .fc-dayGridMonth-button, .fc.weekGridDay-button {
        padding: 8px;
    }
</style>
