<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('SIGAS')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('layout_browser/css/bootstrap.css'))
        ->prependStylesheet($this->basePath('layout_mobile/css/onsenui.css'))
        ->prependStylesheet($this->basePath('layout_mobile/css/onsen-css-components.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('layout_mobile/js/onsenui.js'))
        ->prependFile($this->basePath('layout_mobile/js/jquery-3.1.0.min.js'))
    ?>
</head>
<body>
<?= $this->content; ?>
</body>
</html>
