<?php
/**
 * Created by PhpStorm.
 * User: 400005
 * Date: 13/03/2019
 * Time: 09:28
 */ ?>

<div class="section no-pad-bot" id="index-banner" hidden>
    <div class="container">
        <br><br>
        <h1 class="header center orange-text">Starter Template</h1>
        <div class="row center">
            <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
        </div>
        <div class="row center">
            <a href="http://materializecss.com/getting-started.html" id="download-button"
               class="btn-large waves-effect waves-light orange">Get Started</a>
        </div>
        <br><br>

    </div>
</div>
<!--   Icon Section   -->
<div class="row" id="searchForm" style="">
    <div class="col-md-12 s12 m4">
        <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">Qual especialidade você procura?</i></h2>
            <div class="row">
                <div class="input-field col-11 s6">
                    <i class="fa fa-medkit fa-lg prefix"></i>
                    <input id="icon_prefix_dest" type="text" class="validate typeahead"
                           data-target="autocomplete-options-485ef9ce-70b8-2c17-79b2-91cbbb914c95">
                    <ul id="autocomplete-options-485ef9ce-70b8-2c17-79b2-91cbbb914c95"
                        class="autocomplete-content dropdown-content" tabindex="0" style=""></ul>
                    <label for="icon_prefix_dest" style="margin-left: 70px" class="">Especialidade</label>
                </div>
                <button class="btn-floating btn-large waves-effect waves-light red" id="searchButton"><i
                            class="fa fa-search"></i></button>

                <div class="col-12">
                    <div class="col-6" id="callendar">

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>


<script>
    $().ready(function () {
        let calendar = new FullCalendar.Calendar($("#callendar")[0], {
            plugins: ['dayGrid'],
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'dayGridMonth,timeGridWeek,timeGridDay'
            },
        });
        calendar.render();
    })
</script>