<ons-navigator swipeable id="mainNavigator" page="mainPage.html"></ons-navigator>

<template id="mainPage.html">
    <ons-page id="mainPage">
        <ons-toolbar>
            <div class="center">SIGAS</div>
        </ons-toolbar>
        <ons-tabbar swipeable position="bottom" id="mainTabbar">
            <ons-tab page="tab1.html" label="Inicio" icon="fa-medkit" active>
            </ons-tab>
            <ons-tab page="tab3.html" label="Login" icon="fa-user-circle">
            </ons-tab>
        </ons-tabbar>
        <style>
            .toast {
                opacity: 100;
                background-color: #0f6674;
            }

            .toast-success div {
                background-color: #467447;
            }

            .toast-error div {
                background-color: #a53a39;
            }
        </style>
    </ons-page>
</template>

<template id="tab1.html">
    <ons-page id="Tab1">
        <ons-list class="header-custom" style="background-color: #fafafa">
            <ons-list-item class="input-items">
                <ons-search-input id="search-input" maxlength="20" placeholder="Buscar profissional"
                                  style="width: 70%"></ons-search-input>
                <ons-select id="select-input" style="width: 20%; margin-left: 10px">
                    <option value="name">
                        Nome
                    </option>
                    <option value="React">
                        Especialidade
                    </option>
                    <option value="Angular">
                        Endereço
                    </option>
                </ons-select>
            </ons-list-item>
        </ons-list>
        <ons-row>
            <ons-col style="padding: 0">
                <ons-list id="list-profs">
                    <ons-lazy-repeat>
                        <ons-progress-circular indeterminate></ons-progress-circular>
                    </ons-lazy-repeat>
                </ons-list>
            </ons-col>
        </ons-row>
        <style>
            .search-input {
                background-color: transparent;
            }

            .header-custom, .list {
                background-position: bottom;
            }

            .list-item--longdivider {
                background-image: linear-gradient(0deg, #e3e3e3, #e3e3e3 100%);
            }

            ons-progress-circular {
                width: 50px;
                height: 50px;
                position: absolute;
                left: 42%;
                top: 50%;
            }

            .tweet-header {
                width: 100%;
            }
        </style>
        <script>
            ons.getScriptPage().onInit = function () {
                profissionaisList();
            }
        </script>
    </ons-page>
</template>

<template id="tab3.html">
    <ons-page id="Tab3">
        <div id="form-area">
            <form action="<?= $this->url('login') ?>" method="post" enctype="multipart/form-data">
                <ons-card modifier="material">
                    <div class="title">
                        <h2 class="card__title" style="text-align: center;">Entre no SIGAS para ter acesso a todas as
                            funções</h2>
                    </div>
                    <div class="content">
                        <ons-row>
                            <ons-col width="100%">
                                <div style="text-align: center; margin-top: 30px;">
                                    <ons-if plataform="ios other">
                                        <p>
                                            <ons-input style="width: 80%" modifier="material" id="username"
                                                       name="fEmail"
                                                       placeholder="Email"
                                                       float required></ons-input>
                                        </p>
                                        <p>
                                            <ons-input style="width: 80%" id="password" modifier="material" name="fPass"
                                                       type="password"
                                                       placeholder="Senha" float required></ons-input>
                                        </p>
                                    </ons-if>

                                    <label class="checkbox checkbox--material" hidden>
                                        <input type="checkbox" class="checkbox__input checkbox--material__input"
                                               name="fRem">
                                        <div class="checkbox__checkmark checkbox--material__checkmark"></div>
                                        Lembrar de min
                                    </label>
                                    <p style="margin-top: 30px;">
                                        <button type="submit" class="button">Login</button>
                                    </p>
                                </div>
                            </ons-col>
                        </ons-row>
                        <ons-row>
                            <ons-col width="100%">
                                <div style="text-align: center">
                                    <p>Ainda não possui cadastro?</p>
                                    <ons-button onclick="singupForm(1)">Cadastre-se aqui!</ons-button>
                                </div>
                            </ons-col>
                        </ons-row>
                        <ons-row>
                            <ons-col width="100%">
                                <div style="text-align: center; margin-top: 30px">
                                    <p>Profissional da Saúde?</p>
                                    <ons-button onclick="singupForm(2)">Solicite seu cadastro aqui!</ons-button>
                                </div>
                            </ons-col>
                        </ons-row>
                    </div>
                </ons-card>

            </form>
        </div>
    </ons-page>
</template>

<template id="singupForm.html">
    <ons-page id="singup">
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Login</ons-back-button>
            </div>
            <div class="center">
                Cadastro
            </div>
        </ons-toolbar>
        <ons-card>
            <form action="<?= $this->url('singup') ?>" method="post" enctype="multipart/form-data">
                <ons-row>
                    <ons-col width="100%">
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="md-email" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 80%" modifier="material" id="username" name="fEmail"
                                       placeholder="Email" type="email"
                                       float required validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-key" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 80%" id="password" modifier="material" name="fPass" type="password"
                                       placeholder="Senha" float required validate></ons-input>
                        </ons-list-item>
                        <ons-list-item>
                            <div class="right right-label">
                                <button type="submit" class="button">Cadastrar</button>
                            </div>
                        </ons-list-item>
                    </ons-col>
                </ons-row>
            </form>
        </ons-card>
        <style>
            .list-item__center, .list-item__right {
                background-image: none;
            }
        </style>
    </ons-page>
</template>

<template id="singupProfForm.html">
    <ons-page id="singup">
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Login</ons-back-button>
            </div>
            <div class="center">
                Cadastro de Profissional
            </div>
        </ons-toolbar>
        <ons-card>
            <form action="<?= $this->url('singup-prof') ?>" method="post" enctype="multipart/form-data">
                <ons-row>
                    <ons-col width="100%">
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-user" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" modifier="material" id="info_user_name" name="fName"
                                       placeholder="Nome completo" type="text"
                                       float required validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="md-email" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" modifier="material" id="username" name="fEmail"
                                       placeholder="Email" type="email"
                                       float required validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-key" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" id="password" modifier="material" name="fPass"
                                       type="password"
                                       placeholder="Senha" float required validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-user-md" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-select style="width: 100%" id="info_user_healthcare" modifier="material" name="fCons"
                                        class="select"
                                        float>
                                <select class="select-input">
                                    <option value="">Selecione seu conselho</option>
                                    <option value="1">Conselho de Medicina</option>
                                    <option value="2">Conselho de Odontologia</option>
                                    <option value="3">Conselho de Fisioterapia</option>
                                    <option value="4">Conselho de Fisioterapia</option>
                                </select>
                            </ons-select>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-map-marker" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-select style="width: 100%" id="info_user_healthcare" modifier="material"
                                        name="fConsRegion"
                                        class="select"
                                        float>
                                <select class="select-input">
                                    <option value="">Selecione seu estado</option>
                                    <option value="1">AP</option>
                                    <option value="2">PA</option>
                                </select>
                            </ons-select>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-address-card" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" id="num_reg" modifier="material" name="fNumCons" type="text"
                                       placeholder="Número de registro" float required validate></ons-input>
                        </ons-list-item>
                        <ons-list-item class="input-items">
                            <div class="left">
                                <ons-icon icon="fa-plus-square" class="list-item__icon"></ons-icon>
                            </div>
                            <ons-input style="width: 100%" id="espec" modifier="material" name="fEspeciality"
                                       type="text"
                                       placeholder="Especialidade" float required validate></ons-input>
                        </ons-list-item>
                        <ons-list-item>
                            <div class="right right-label">
                                <button type="submit" class="button">Efetuar solicitação</button>
                            </div>
                        </ons-list-item>
                    </ons-col>
                </ons-row>
            </form>
        </ons-card>
        <style>
            .list-item__center, .list-item__right {
                background-image: none;
            }
        </style>
    </ons-page>
</template>

<template id="professionalsPage.html">
    <ons-page id="professionalsPage">
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Busca</ons-back-button>
            </div>
            <div class="center">Resultados</div>
        </ons-toolbar>
        <ons-row id="fResultados">
        </ons-row>
    </ons-page>
</template>

<template id="detailsPage.html">
    <ons-page id="detailsPage">
        <ons-toolbar modifier="noshadow">
            <div class="left">
                <ons-back-button>Busca</ons-back-button>
            </div>
            <div class="center"></div>
        </ons-toolbar>
        <ons-row id="fInformacoes">
        </ons-row>
        <ons-bottom-toolbar onclick="checkDates($('#profid').val())">
            <ons-row>
                <ons class="col"></ons>
                <ons class="col" style="padding-top: 10px">SOLICITAR PROCEDIMENTO</ons>
                <ons class="col"></ons>

            </ons-row>
        </ons-bottom-toolbar>
        <style>
            .profile_button_bar_agenda, .profile_button_bar_pac,
            .profile_button_bar_profile {
                text-align: center;
                font-size: 26px;
                /*height: 50px;*/
                line-height: 40px;
                border-top: 1px solid rgba(187, 187, 187, 0.51);
                background-color: #fafafa;
            }

            .profile_button_bar_agenda ons-col {
                width: auto;
            }
            .profile_upper {
                padding: 14px 6px 14px 16px;
                background-color: #fafafa;
            }

            .custom-button {
                color: #c3c3c3;
                width: 100%;
                background-color: #fafafa;
                border-radius: 0;
                box-shadow: none;
            }

            .custom-button.active {
                color: #5fb4f4;
                border-bottom: 2px solid #5fb4f4;
            }
        </style>
        <script>
            ons.getScriptPage().onInit = function () {

            }
        </script>
    </ons-page>
</template>

<?= $this->headScript()->appendFile($this->basePath('plugins/controllers/front-controller.js')) ?>